### ISSUE TITLE
Human Error/Wrong Email Address

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#101]
![screen shot 2015-08-10 at 1 06 23 pm](https://cloud.githubusercontent.com/assets/11848699/9179221/b28f0f5a-3f60-11e5-9a2d-fb5f684df1e4.png)

Any easy way to notify the user that they have typed it in wrong?

--Probably clicking link for email confirmation through their email for First Trip, registering that email into our system.

**Comment by markstm17** [comment]
She spelt her last name wrong in the email (Sinkula)

**Comment by markstm17** [comment]
![screen shot 2015-08-10 at 1 07 24 pm](https://cloud.githubusercontent.com/assets/11848699/9179272/05e31e62-3f61-11e5-89f5-0caf974b6535.png)

**Comment by markstm17** [comment]
Forgot C in .com

**Comment by markstm17** [comment]
Besides that, EVERYONE else has received the email notifications.

**Comment by freindst** [comment]
After we added a email validation process, situation will be changed, and user will have to provide a valid email address. Besides, I will add an additional function to change username. It is because after user changes username, he will be forced logging out.

**Comment by duncangraham** [comment]
I already added email verification. Both of those emails are a valid format. There isn't any easy way I can think of to solve for human error. Many sites require users to click an activation link sent to the provided email to make sure they typed it in correctly. I'm always annoyed by this though. I don't think we should punish the 90% that's sharp enough to type correctly. 

Here's what we should do:
1. bus reservation made
2. redirect to confirmation screen
3. on confirmation screen have the message read 'Congrats! We've sent a confirmation to your email: **EMAIL LARGE AND IN BOLD**. '
4. link below: ''That's your email, right? If not, you can change it here"
5. here takes them to the account edit page

**Comment by markstm17** [comment]
I think this process is great. Can we have the confirmation emails sent and updated for when pledged are made for Buffett and that Confirmation Page finished too?

@duncangraham I like this 5 step process better then signing in to your email to click the link to verify. Lets test this out!

**Comment by freindst** [comment]
what I mean is email verifying. After register a user account, user needs to activate this account through links in the email in order to fully activate the account. In this way, user have to provide a valid and correct email.

**Comment by markstm17** [comment]
So both of you guys have a different approach to this @freindst and @duncangraham and I'm not opposed to either one, with the focus being to correctly get the right email. I say we go with whatever is less work right now. This is for the first bus/trip and we will get feedback either way, so lets move swift and fast with whatever is easier and more efficient.

Duncan's 5 steps above or Blade's activation of account through link sent to email

**Comment by duncangraham** [comment]
Lets go with my execution for now. we had 51 people sign up to test Argo and only 2 messed up their emails. It seems like poor product design to punish the other 49 by making them deal with verifying their correct email.

My one reservation is that down the road someone may maliciously enter incorrect emails, but I'm not sure for what reasons. We should talk about this eventuality in a security ticket though, since it's out of scope here.

**Comment by markstm17** [comment]
Based upon your execution and work @duncangraham , we should be good to go!

![screen shot 2015-10-20 at 8 21 12 pm](https://cloud.githubusercontent.com/assets/11848699/10625381/36065d90-7768-11e5-9721-0e83cd10861b.png)

**Comment by markstm17** [comment]
Closing
