### ISSUE TITLE
One person buying multiple tickets 

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#103]
I started typing, we NEED to have this option, then I started to ponder it.

What are your thoughts @duncangraham and @freindst for having ability for one person to pledge for multiple seats (or having option to do so) for other friends. 

Through experience on Eventbrite and just in general, often times boyfriends pay for two tickets (him and his girlfriend -or visa versa)

There have been plenty of times where people buy 4-10 tickets for their friends too. 

If we do this, I think we need to have the user who is buying multiple tickets put the names of the other members in fields that pop up pending number of tickets being bought.

Thoughts?

**Comment by freindst** [comment]
It will be a big change to our models. Waiting for future work

**Comment by markstm17** [comment]
We will push this off until after our first trip with Buffett. It is fine that it is a change we will work on in the future (there are much more important things right now) but I'm very confident that we will have user feedback that says they'd like that as an option. People like being able to buy multiple tickets for their family/friends, especially if there are a limited number of spots. Here is one example from the last trip I did

![screen shot 2015-08-10 at 10 31 57 pm](https://cloud.githubusercontent.com/assets/11848699/9189596/34e6fa5e-3fb0-11e5-975a-837e3bf9dbaf.png)

**Comment by markstm17** [comment]
![screen shot 2015-08-10 at 10 32 20 pm](https://cloud.githubusercontent.com/assets/11848699/9189599/46f140d8-3fb0-11e5-9155-520293d16646.png)


This is from the same trip, a few people bought multiple tickets

**Comment by freindst** [comment]
I think we could let user to choose tickets number, and he can fill in passenger information to each tickets after pledging.

**Comment by markstm17** [comment]
@freindst does that take a long time to implement? Your previous comment was that it will be a big change to our models and waiting for future work.

Your comment yesterday **"I think we could let user to choose tickets number, and he can fill in passenger information to each tickets after pledging."** is exactly how I'm envisioning it.

**Comment by freindst** [comment]
It will take a while, perhaps in one or two day. I have to find a way not damage to much to our existed system.

**Comment by markstm17** [comment]
If that's the case, then don't worry about it right now @freindst 

That can be a goal after our first bus
