### ISSUE TITLE
Junk Mail Folder

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#104]
Is there any way we can not let these emails go to their junk mail, or will it be the users responsibility to check? 

![11846035_10154099014687598_1950936701_n](https://cloud.githubusercontent.com/assets/11848699/9179705/e5e10a4a-3f63-11e5-8e9b-e2f6b6b380af.jpg)

**Comment by markstm17** [comment]
![11874184_10154099014657598_1509089394_n](https://cloud.githubusercontent.com/assets/11848699/9179707/f1a15150-3f63-11e5-9b76-924ce05c71c6.jpg)

**Comment by freindst** [comment]
There is no way to deal with it. It depends on how user's email provider treat auto email. Anyway, we can add notification in user account part, like message system within the website.

**Comment by duncangraham** [comment]
yea, I believe we're using sendgrid which is great at getting past junk folders. but there's only so much we can do.

the best way to handle this now is with language. on the confirmation page, we should have a checklist

##didn't get an email?
- make sure you entered the correct email address
- check your junk mail

**Comment by markstm17** [comment]
I'm going to make this part of the Milestone for Buffett @duncangraham

**Comment by markstm17** [comment]
This isn't necessary for these two Buffett buses, but I do like what you said 11 days ago @duncangraham 

Keeping open until next week where we can maybe implement/test this

**Comment by markstm17** [comment]
Going to close for now based upon Sendgrid's ability to get past Junk Folders

Reopen if you feel like we need to @duncangraham
