### ISSUE TITLE
Google Map Integration on Event/Bus Details page

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#11]
Seeing the Pick Up Address and Destination Address through Google Maps (Like on your Meteor site @duncangraham )

**Comment by duncangraham** [comment]
this is not a priority for the DMB trip as I see it now, I'll hit this after the account and other backend work is completed.

**Comment by markstm17** [comment]
I'm going to post this here now as we talked about tonight per our conversation over the phone

Need to update map integration on trip details/pledging/POM page

![12177768_10154274292717598_1290140938_n](https://cloud.githubusercontent.com/assets/11848699/10624293/a44c27a0-775c-11e5-8300-63ba918675d5.jpg)

**Comment by duncangraham** [comment]
this happened
