### ISSUE TITLE
Modify business model and screen flow

### ISSUE THREAD

**Issue by freindst** [ArgoBus/Argo-Project-V0#112]
We will make our pledging process better.

Step | Two Trips | One Trip
------------ | ------------- | -------------
1 | view the trip list | view the trip list
2 | select trip | select trip
3 | choose to make a reservation | choose to make a reservation
if not logged in | --- | ----
3.5 | user log in or sign up | user log in or sign up
4 | jump to a page to pledge the trip | jump to the page to pledge the trip
5 | provide payment info | provide payment info
6 | finish pledging | finish pledging

**Comment by markstm17** [comment]
Closing @duncangraham
