### ISSUE TITLE
Date Time problem

### ISSUE THREAD

**Issue by freindst** [ArgoBus/Argo-Project-V0#113]
@duncangraham I know you changed db model about datatype in pick up time and drop off time fields, and you also added moment module in order to get hour and minute instead of full date-time. It is good as fits our model right now, but I want to change back:
 1. There is a interesting thing point in display time in html. All full date (e.g. 2015-08-13 05:00:00) is  time at GMT-0000, and when displayed out, it will be changed to local time automatically. So, originally, I store the whole time object in the database It will be different if we add date and time together when we are using HH:MM as time format.
 2. In the admin page(/admin), I used date() function to compare current time and pick up time. As pick up time is only a time string (HH:MM), an error comes out.
 3. We are treat pick up time is at the same day as event date right now. However, as our business expands, pick up time may not be the same as event date in future Therefore, keeping pick_up_time as a full date datatype field means we might have less work afterwards. As a matter of fact, I have to change codes in order to fit your updates, which means we both have to do more work.

If you insist to change the fields from datatype date to time, I will change my code later.

**Comment by freindst** [comment]
Now everything works good without error. If you want to change model again, check all pages.

**Comment by duncangraham** [comment]
stale
