### ISSUE TITLE
How many days in advance should a bus be made?

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#116]
This needs to be effectively communicated to organizers and reflected in the product. (i.e. the datepicker shouldn't allow you to choose the day of)

**Comment by markstm17** [comment]
Agreed. After Buffett, we should do a minimum of 7 days. From my experience that is more then enough and we can learn from it through more trips through our system

**Comment by duncangraham** [comment]
ok, then I need to update the datepicker code. next actions are on me

**Comment by markstm17** [comment]
Let's implement this at a 7 **business day minimum** moving forward @duncangraham 

We can always change and update if  and when necessary, but 7 business days is more then enough time for me on my end to make something happen (Booked bus for Green Bay 5 days beforehand)

Let me know if you have questions

**Comment by duncangraham** [comment]
![date](https://cloud.githubusercontent.com/assets/865298/10645133/fdbe1e68-77e0-11e5-96ee-68f9ccbdc9fc.gif)

this has been completed and will be bundled in #226 

we need to add help@argobus.com to the email list
