### ISSUE TITLE
brewers stadium bus statistics

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#122]
**If we could get the dataset for how many passes were sold per game in 2014 that would be golden.**

- how many buses can they fit on the lot? 
- what are the trends per week/month?
- are there spikes for certains teams?
- are there any anomalies?

## next steps
can you try to get the bus pass data @markstm17? If you pitch it to the stadium that we are a bus company trying to increase capacity and the bus pass data could help us I don't see why they wouldn't share the data.

### formats
Comma separated values (CSV) is best, though excel or SQL also works.

**Comment by duncangraham** [comment]
ask for the bus pass data, then back off to 2014, then back off to a month or some sample

**Comment by duncangraham** [comment]
excel spreadsheet, CSV, or SQL works

**Comment by markstm17** [comment]
Just called my contact with the Brewers and he said he'd talk with his manager about giving me/us info. He said he doesn't know how much info they would be willing to give out but said he help out in any way possible. 

I told him I'll follow up with him early next week and set up a meeting with him for me to come in, show him our website and what we are working on as well as to ask for the specific info and data that we need, so this week we should be specific and compile all of the questions together and figure out all the stuff we will need:

-how many buses can they fit on the lot at capacity?
-how many total bus passes did they sell in 2014?
-how many of they sold so far in 2015?
-how many are sold on weekend games vs weekday games?
-spikes for certain teams?
-how many are bought in advance vs buying the day of the game?
-what determines the price you guys set? $40-$75 range

**Comment by duncangraham** [comment]
ok sounds great @markstm17 

if you can communicate that we're trying to make some sweet business synergy (us succeeding means they succeed) and push for the full dataset, we could do some awesome shit with it. 

I'd be interested in knowing what their concerns are for the data. we could propose to anonymize it or (and don't give this up without some solid wins) we could sign an NDA and only use the data to learn about the market (rather than exposing it in presentations)

**Comment by markstm17** [comment]
I will definitely do that @duncangraham. 

I'll touch base about this when the meeting is set up

**Comment by markstm17** [comment]
Meeting with my contact with the Brewers on Wednesday Aug 26th at 10:00am @duncangraham

**Comment by duncangraham** [comment]
Could you update this @markstm17?
