### ISSUE TITLE
clean up app.js

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#123]
there's a ton of old code from the hackathon to be removed, and I'm sure there are other parts that could be cleaned up.

**Comment by markstm17** [comment]
How is this looking @duncangraham ? Waiting until after Buffett for this??

**Comment by duncangraham** [comment]
yea, this isn't a priority. punting till i get a free moment

**Comment by duncangraham** [comment]
this happened.
