### ISSUE TITLE
create Argo github organization

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#124]
# We need to move this off of hivemind's org so we can scale from here more effectively.
also, getting the github charge onto the calibadger card would be good too.

--

once this organization is made I want to move this repo there.
i also want to create these repos as well: 

- business
- growth (user acquisition strategies)
- recruiting (to post tickets on people we might potentially bring on the team)

boxing tickets into repos will make it easier to parse what's going on and our priorities as well as scale 

_any other repo ideas @markstm17? no need to make them for their own sake, and the fewer the better. but if you think there's anything i've missed i'm all ears._

## next steps
@markstm17 [makes a new github organizaztion](https://help.github.com/articles/creating-a-new-organization-account/)

**Comment by markstm17** [comment]
This will be a priority of mine after Buffett this weekend. Will start this Sunday/Monday of next week

**Comment by markstm17** [comment]
@duncangraham created the organization and invited you (ArgoBus). Bronze level, 10 private repos. Will start transferring repos over after your lead this week. Will keep ticket open until you transfer some over, you'll close this ticket when you're done.

**Comment by markstm17** [comment]
Just created the new repos for ArgoBus @duncangraham

**Comment by markstm17** [comment]
I'll let you close after you respond @duncangraham 

1. I haven't seen you as a member of ArgoBus Org yet. Do you need me to resend you an invite?

**Comment by duncangraham** [comment]
this happened
