### ISSUE TITLE
Number of Users not matching up with Current Passengers

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#133]
![11911552_10154123577867598_1609349811_n](https://cloud.githubusercontent.com/assets/11848699/9358244/99a9bde0-4650-11e5-97f1-57da76935e9c.jpg)

--I know you don't like the screen shots but bare with me @duncangraham, I think it is really the only way to deal with the problem and physically show you.

It says it is on passenger number 12, but there are only 8 passengers signed up (names and emails)

**Comment by markstm17** [comment]
![11896982_10154123577962598_1257784272_n](https://cloud.githubusercontent.com/assets/11848699/9358308/dfec61a4-4650-11e5-8cca-f7ebac80bcf8.jpg)

**Comment by markstm17** [comment]
![11913311_10154123578022598_767037273_n](https://cloud.githubusercontent.com/assets/11848699/9358316/f32fca6c-4650-11e5-8380-e2dd11f6ce92.jpg)

**Comment by markstm17** [comment]
![screen shot 2015-08-19 at 9 02 38 am](https://cloud.githubusercontent.com/assets/11848699/9358349/21f5a786-4651-11e5-899f-ca9bea23d489.png)

The email associated with Chris Pierson (that Jake Corning bought) doesn't show up as a customer on Stripe. (jcorn3@wi.rr.com)

In addition, the other problem (Abbey Hayden when her name was null, null) is not a customer through Stripe.

**Comment by duncangraham** [comment]
for this lets sync on chat @markstm17

**Comment by markstm17** [comment]
This relates directly to #224 

Closing this because it is the same problem/issue as referenced ticket @duncangraham
