### ISSUE TITLE
Pledging for Multiple Tickets

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#134]
Because our current users are limited to purchasing only 1 bus ticket through their own profile, Jake as the recent example made three profiles (for himself, Chris and Caitlyn) and paid for all three users. **Because of this, Caitlyn and Chris will not receive emails about the price dropping, Jake will get three different emails since he used three of his own emails in this process example**

**Comment by duncangraham** [comment]
This is another task that needs to happen as soon as bugs and user roles are figured out.

**Comment by markstm17** [comment]
This is another aspect that we need for our customers/users, but my question to you @duncangraham  is how important is this right now?

From experience, people always want to do this, because it is convenient. If there are also a limited number of spots left, friends and family want to make sure that their entire group gets a seat and gets on. Examples include:
- Boyfriend/girlfriend buying (now pledging) two tickets
- Family members buying (now pledging) them for each other (This happened through Argo for Buffett, one of the "pledges" individually put her credit card in for ALL 9 profiles created for her family/friends) 
- Friends buying (now pledging) for each other


# Argo Bigger Goal
Our goal is to have EVERYONE create their own profile and input their own credit card information because we are making this process accessible at the press of a button, **ONCE** they have a profile set up and their CC info stored in our system

# Question for Duncan
What type of incentive do we want to put in place so that people **WANT** to sign up, have a profile and **PLEDGE** for themselves because it's extremely easy through Argo, as well as the benefit/incentive they receive for **PLEDGING** themselves and not having someone else pledge for them

**Comment by markstm17** [comment]
This relates to #103 

I'm going to close that ticket because its redundant (One person buying multiple tickets)

**Comment by markstm17** [comment]
This NEEDS to be done. Some of the biggest feedback from this bus this weekend

One of the pledges created 3 different accounts and put all three on his card and had his two friends pay him cash on the bus


# From Argo Perspective

We want everyone to have their own account and we want more and more people to be users and pledges though!

#### Need incentives to pledge for yourself for your events

BUT

#### Need to have the option to buy/pledge/purchase multiple tickets

**Comment by duncangraham** [comment]
this happened!!!!!!

![di9bc61](https://cloud.githubusercontent.com/assets/865298/11231140/624bc64e-8d5a-11e5-98ed-bd025fb8511f.gif)
