### ISSUE TITLE
Price-o-meter

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#135]
![screen shot 2015-08-19 at 9 35 47 am](https://cloud.githubusercontent.com/assets/11848699/9359226/c51fe49a-4655-11e5-8639-728fdfc4bd91.png)

***Not important until after Buffett***

On the right side have a thermometer or price-ometer with starting price, current price and the lowest it could be

**Comment by markstm17** [comment]
Example:

Was $45
Is $35
Could be $20

**Comment by duncangraham** [comment]
this will be a super fun feature to add, I'll likely not start development on it till september

**Comment by markstm17** [comment]
I'm really excited for this. I'm assuming the visual will be huge (from a UX standpoint) and I know it'll be fun for you to make. Sounds good @duncangraham

**Comment by markstm17** [comment]
@duncangraham I'd say that this is a higher priority then the **ENTIRE** low priority checklist on #182 . This feature of Argo should be focused on after the higher priority checklists on #182 . This is a visual that again communicates with and educates our organizers/customers/users. 

I'm extremely confident to say that the two main reasons I won Launch Milwaukee back in June was because of:
- The bigger picture idea of what Argo can be and the fact that we are trying to solve a big and outdated problem/process
- The price-o-meter visuals 
There were two teams that were decently farther along that weekend with what they built over the 24-36 hours during Launch Milwaukee, but the judges/investors saw the bigger picture of Argo. 

After "testing" the pledge process at the beginning of August before we officially did Jimmy Buffett on August 22nd, this was was the founder of Launch Milwaukee texted me after he pledged through what you've built in Argo

![12071689_10154235560857598_977656573_n](https://cloud.githubusercontent.com/assets/11848699/10251175/bb6edd68-68f4-11e5-9a8c-f8d35e7c2864.jpg)

--

### I know we are on the same page with how essential this will be, I know you'll have a blast creating it, and I know it will make a difference for our users. I just wanted to stress that it should be the next thing we focus on after the home page, FAQ and TOS

**Comment by markstm17** [comment]
## Old screen shot versions of the price-o-meter from Launch Milwaukee 


![screenshot2](https://cloud.githubusercontent.com/assets/11848699/10251404/0ab73414-68f6-11e5-8ab0-49a39557c6bc.png)

This is the page for the specific "Kenny Chesney" specific bus/event. (There is no price-o-meter with this screen shot, obviously)

--

## Here is the progression of the price-o-meters on the home page as more and more pledges sign up

![screen shot 2015-10-02 at 11 06 47 am](https://cloud.githubusercontent.com/assets/11848699/10251661/f8dce656-68f7-11e5-9928-3971cf6d5167.png)

--

![screen shot 2015-10-02 at 11 07 07 am](https://cloud.githubusercontent.com/assets/11848699/10251666/00401d96-68f8-11e5-889f-29e968484e48.png)

--

![screen shot 2015-10-02 at 11 07 30 am](https://cloud.githubusercontent.com/assets/11848699/10251672/0b39ebdc-68f8-11e5-9d63-98c83e3c83a5.png)


#### Beyond jacked to see your creativity and design skills around this part of the Argo project. I know you'll make this look awesome

**Comment by duncangraham** [comment]
Related to #187- this is a bigger feature and we need to prioritize

**Comment by markstm17** [comment]
When you make our visual communication tool for Argo, the price-o-meter should be on the Current Trips page to the right where there is white space. Screen shot from Current trips page for the Packers game I just put together.

You clearly see that the current price is $160 per person, that is communicated awesomely. We also have to communicate that the bus WON'T BOOK until 21 people or $50 per person is booked (That's the threshold I picked). This can be a different color, bold, bigger font through our price-o-meter 

![screen shot 2015-10-05 at 3 09 25 pm](https://cloud.githubusercontent.com/assets/11848699/10292187/6b66ffc2-6b73-11e5-855e-2ef2d2d82465.png)

**Comment by markstm17** [comment]
Here is the threshold and the price breaks for the public bus for the packers vs chargers game that I just put together. The bus will cost Argo (us) $800-$900


![screen shot 2015-10-05 at 3 18 57 pm](https://cloud.githubusercontent.com/assets/11848699/10292370/796bea6e-6b74-11e5-9972-3e3b1f2f047f.png)

**Comment by markstm17** [comment]
So after talking with people today about the Packers vs Chargers bus specifically (That I'm trying to organize for October 18th), people don't get why it says $160 right now (above two comments). It is communicated very poorly (the perception of the cost per person)
- It is a horrible turn off for the early adopters 

Previous way of communicating based upon my comments above:

> Example:

> Was $45
> Is $35
> Could be $20

We need to be able to communicate the following through the Price-o-meter:

**There is NO RISK to pledge unless threshold is hit**

- Threshold cost per person
- Current cost per person
- Cheapest cost per person

**Comment by markstm17** [comment]
@duncangraham we need to create the price-o-meter the way we discussed over the phone today.

# Goals With P-O-M
- Argo sets public trips as a 40% capacity default threshold (22 people out of 56-for motor coach, and 20 out of 50-for yellow school bus)
 - New price drop at 50% capacity (28 people, and 25 people)
 - New price drop at 75% capacity (42 people and 35 people)
 - New (final) price drop at 100% capacity (56 people and 50 people)

We need to communicate that there is no risk to be one of the first 20-22 people to pledge because if we don't get 40% of people to commit, it will not become a Live bus.

Thoughts and ideas for how this will look, how long it will take?

**Comment by duncangraham** [comment]
Lemme put some ground work in over the next 2 days, and check in before friday night.

Most likely, this will touch many aspects of the product and require a lot of work on the front and back ends.

Also, gotta figure out the bugs happening with the bus thats going on sunday.

**Comment by markstm17** [comment]
![12177768_10154274292717598_1290140938_n](https://cloud.githubusercontent.com/assets/11848699/10624790/ab5b9a08-7761-11e5-95f6-1e54be50429f.jpg)

### I know I've posted your screen shot of P-O-M on #167 earlier but thought this fit in here as well. 


The below comments are from a previous post, which I'm closing #66, but this information is still relevant and we may need to update one part of it (showing list or available spots on the bus)
- Showing in top right corner, or somewhere where it stands out that the current capacity is 10/56 spots
 - Showing the **10/56** as an example is what the entire group requested on the bus this past Sunday


## All of the main questions from #66 

> Show if bus is a "green light" or not yet (Bus is booked and Live)

At this stage, all buses should be green lit. Let's add this soon.
**- You have been able to add this with our 40% threshold! WOOHOO DUNC**

> How many spots are on the bus

agreed
**- This is what I'm referring to above with the 10/56 example**

> What the current cost is

agreed
**- You will have had this implemented through our Price-o-meter!! WOOHOO!**

> How much money the group has saved from when it became a Live bus, to where cost is now/currently, to what it would be at Max capacity

not necessary right now, but this is nice and we can add soon.
**- Agreed, still not necessary right now, people will be able to see**

> All details for trip -Pick Up time -Pick Up Address -Destination -Drop off time

yeap
**- Still need to finish this in most recent screen shot above, especially with Map, also referring to #11 

--

this is what the page currently looks like

<img width="1390" alt="screen shot 2015-08-05 at 10 54 35 am" src="https://cloud.githubusercontent.com/assets/865298/9093342/749d495e-3b60-11e5-8af6-85ac3271ab74.png">

I'll work on updating this today.

**Comment by duncangraham** [comment]
On the same topic, I met with @sohlis last night and he said that it was unclear that the pledge amount would change over time. working on this today

**Comment by duncangraham** [comment]
<img width="435" alt="screen shot 2015-10-23 at 11 16 05 am" src="https://cloud.githubusercontent.com/assets/865298/10701255/794cf54e-7977-11e5-9cd6-5e30276b9003.png">

added the note above the module, which I think clears it up a bit-- I'll do some user testing though to make sure it's clear

**Comment by duncangraham** [comment]
this was 🚢-ed

**Comment by sohlis** [comment]
woot!
