### ISSUE TITLE
Food and Drink Field

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#136]
After these buses we need to change the Food and Drink wording to communicate it more effectively that it is ALLOWED and that we aren't bringing it for everyone. 

A few people thought I was supplying food and drink for everyone because it said Yes on the event description

**Comment by duncangraham** [comment]
how many buses do you organize that don't have food and drink? is this field redundant?

**Comment by markstm17** [comment]
From what I've personally done this summer since April, I'd say 80% have had food/drink on it.

That will always be an option the bus company gives to the customers (same with us for Argo), but we need to know if the group is brining food/drink because it affects the cost. 

When signing up through Argo, we need to better communicate what is being provided in the cost. (Are we allowing food and drink or are we providing food and drink) That was the biggest miscommunication with some of the users.

**Comment by duncangraham** [comment]
ok then I think the correct way to deal with this is opposite what we're doing now.

rather than a checkbox to bring food/drink, lets switch to one that says 'no food or drink on bus ($100 discount)'

**Comment by markstm17** [comment]
Perfect. Easy enough. Always add $100 for the sake of it right now unless they explicitly say they won't have food/drink

**Comment by duncangraham** [comment]
Ok, then for now, just add this when you create the pricing teamplate's @markstm17. once you're :+1: feel free to close this

**Comment by duncangraham** [comment]
@markstm17 is there anything else that needs to be done here?

**Comment by markstm17** [comment]
If by clicking on 

![screen shot 2015-10-02 at 3 45 44 pm](https://cloud.githubusercontent.com/assets/11848699/10257395/b446956c-691c-11e5-885e-fdbc36029e0a.png)

results in the organizer and the group being charged an additional $100 to whatever the rental time price estimator gives ((8 hours *$50)= $400 + $100= $500) then there should be nothing else, _right now_ (Some bus companies may charge more as we continue to grow, we will learn)

I'll let you close if it is up to date and imbedded with the price estimator #167

**Comment by duncangraham** [comment]
<img width="1004" alt="screen shot 2015-10-02 at 4 27 11 pm" src="https://cloud.githubusercontent.com/assets/865298/10259871/7a1c8be8-6922-11e5-96d1-61002c693ede.png">

for now, I've added a bit of communication to the button itself. once the estimator is done I'll include that in the the submit button. 

![fuckyea](https://media.giphy.com/media/RrVzUOXldFe8M/giphy.gif)
