### ISSUE TITLE
Cadence Bryant (Customer for Rookies Bus for bus trip #1) never got Confirmation Email

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#137]
So I don't know if it was a little glich/bug or what it was/is but I went over to Cadence Bryant's house to walk her through the process because she was having problems and trouble with signing up.

I looked at her email and she NEVER got a confirmation email but she DID get a lowering the price email (from $45 to $35)

Here are two screen shots from different times of the day. This one does not have Cadence

![screen shot 2015-08-19 at 9 35 47 am](https://cloud.githubusercontent.com/assets/11848699/9373989/157e6f78-46b6-11e5-99a0-1e80d0529e4f.png)

**Comment by markstm17** [comment]
![11880796_10154124913782598_340839101_n](https://cloud.githubusercontent.com/assets/11848699/9374013/5c4e7f10-46b6-11e5-9e90-b491f81c1eb0.jpg)


This one does

**Comment by markstm17** [comment]
She is a customer on Stripe, so it must have went through, but there was definitely a little glich for at least a while. She never had the confirmation email, so maybe it came through afterwards.

**Comment by duncangraham** [comment]
this is most likely a send grid issue. Speaking of, we should make sure we have full control of the sendgrid account. will look into this this week

**Comment by markstm17** [comment]
Blade just messaged us on the TrevDev slack the account info, but he recommended to make our own SendGrid account

**Comment by markstm17** [comment]
This shouldn't be a problem anymore.

Closing because our SendGrid integration has been fine and because we have our own account @duncangraham
