### ISSUE TITLE
Missing Customers from Current Passengers on Stripe Dashboard

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#139]
Two customers on the Rookies bus have had their confirmation email and have signed up but are not listed on Stripe:

Abbey Hayden 
and 
Chris Pierson

Abbey Hayden did have the initial null, null problem
And
Chris Pierson was signed up by a friend through a friends email address who ended up getting three confirmation emails

**Comment by markstm17** [comment]
![11896982_10154123577962598_1257784272_n](https://cloud.githubusercontent.com/assets/11848699/9386848/13a24c48-4723-11e5-9a40-ece52e16ed89.jpg)

I know you don't like screen shots, but I think this best describes the users experience @duncangraham

**Comment by duncangraham** [comment]
yea, I gotta look into this today

**Comment by markstm17** [comment]
This should be fixed
