### ISSUE TITLE
datepicker CSS only working on local

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#141]
figure out why the datepicker styling is working in development but not on argobus.com

--

<img width="1392" alt="screen shot 2015-08-20 at 7 35 22 pm" src="https://cloud.githubusercontent.com/assets/865298/9400138/ad654a7a-4772-11e5-9cf7-a9378ed940b0.png">

**Comment by markstm17** [comment]
This works on argobus.com

Closing
