### ISSUE TITLE
Manually charging all of our Customers on Stripe for 2 Buffett buses

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#142]
It did not automatically charge the group through our Stripe account after I charged the trip on Saturday.

Per our conversation I think it more has to do with the format of the cost and how we inputted it (.35 cents vs $35). Let's make sure to fix this asap too! 

This is priority and needs to be done today @duncangraham

**Comment by duncangraham** [comment]
This was my bad for not knowing stripes charge format (though we should have caught this during testing). @markstm17 I'll fix the code, would you mind going through stripe and making the manual charges? you'll go the the customer list, check the logs for how much the user was supposed to be charged and then make a manual payment.

--

![makecharg](https://cloud.githubusercontent.com/assets/865298/9447498/8cde7d80-4a4c-11e5-8cbf-540c659eb1b1.gif)

**Comment by markstm17** [comment]
I can do this @duncangraham

**Comment by markstm17** [comment]
This is finished. Check out our Dashboard now! Woohoo! 

Creating two new tickets for you to see how everything went @duncangraham
