### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#143]
As we talked about on Friday, there were two Packers Trips that were created and bypassed my authority on the admin side to approve of the trip. The organizer was "unknown". 

This needs to be tightened and fixed.

**Comment by duncangraham** [comment]
This is what I'll be working on today. for now there will only be 2 roles

## admin
- ability to see more pages, create buses

## user
- ability to reserve seats on a bus

**Comment by duncangraham** [comment]
this happened. @markstm17- you and i are admins, everyone else is a user.
