### ISSUE TITLE
Change $.25 to $25.00 through Argo for Stripe

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#144]
Great learning experience and honestly glad that we/I had to manually do this. Good to know just for the future and when things pop up.

Through doing this we learned some other things too! (next tickets)

But let's automate this @duncangraham (I know it is self explanatory and we talked about it, but thought I'd make an official ticket for it)

**Comment by duncangraham** [comment]
fixed this. Stripe uses the ['smallest currency unit'](https://stripe.com/docs/api/node#create_charge) which is cents in our case.

The current fix is to multiply the charge by 100. i wonder if the better solution would be to save the cents in the database though. for now this works though.

We should make a test bus and charge a card to make sure this is working in production correctly. once thats done you can close the ticket

**Comment by markstm17** [comment]
I'll do that right now then @duncangraham so we can test it

**Comment by duncangraham** [comment]
what were the results?

**Comment by markstm17** [comment]
I don't think we ever actually tested this because directly after Jimmy Buffett (Aug 22nd) we had the talk about moving forward or not via skype, then you were in Colorado for an extended weekend and then I traveled out to SF when we were kind of in a "stand still"

Do we still need to do this test bus @duncangraham ?

**Comment by duncangraham** [comment]
I think testing would be prudent-- wanna take point on that @markstm17?

**Comment by markstm17** [comment]
Just created a Brewers Test Bus to test this out. I was able to create a bus/trip, but I can't confirm the bus right now, I didn't get an email to confirm it

**Comment by markstm17** [comment]
To change to Test mode, do we simply change it through Stripe then @duncangraham ? I'm assuming Stripe has that function.

**Comment by duncangraham** [comment]
you won't be able to change the argobus.com to test mode. the modes are set by keys in the app. In the development version of the app I use the test keys. in production I use live keys

**Comment by markstm17** [comment]
Everyone that was charged for the Packers vs Chargers bus was charged $50 (Only had 8 customers)

Our Stripe transfer and business account just got + $386.
- Stripe's % was the $14 or 3.5%

Whatever you did after Buffett should have fixed this @duncangraham . Great work!
