### ISSUE TITLE
Customer had no Credit Card Information in Stripe

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#146]
![screen shot 2015-08-24 at 3 58 49 pm](https://cloud.githubusercontent.com/assets/11848699/9452837/35b70808-4a7c-11e5-9bf9-09271bbf41cf.png)

This customer had nothing to charge. There was no card information registered. Fortunately for this customer, I charged her husband/boyfriend $50, instead of both of them $25

**Comment by duncangraham** [comment]
this shouldn't be possible anymore because of #165
