### ISSUE TITLE
Changing URL through Stripe to ArgoBus

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#147]
![screen shot 2015-08-24 at 4 51 21 pm](https://cloud.githubusercontent.com/assets/11848699/9453549/af3114c2-4a80-11e5-9b2b-9ac7e1f39051.png)

This is exactly why I wanted to charge myself, to simply see what it would actually look like on the UX side when getting charged. Not huge priority (I'll handle if there are questions from users this past weekend), but customers will be expecting something "Bus related". Right not the "Argo Brand" isn't there and that'll be our job moving forward, but there are two things here:

- maybe a little confusion when they see argo.meteor charged on their CC
- a missed opportunity to extend brand with ArgoBus

**Comment by markstm17** [comment]
**Rally Bus' Credit Card Authorization**

![screen shot 2015-09-25 at 2 19 19 pm](https://cloud.githubusercontent.com/assets/11848699/10110069/7ac33a5c-6390-11e5-86d3-d9dd49ac84ee.png)

Still not a major priority right now, but definitely still need to keep this ticket open. 

This is a form of communication to our Users and Customers.

**Comment by duncangraham** [comment]
You should be able to go into stripe and change this whenever

**Comment by markstm17** [comment]
I'm going to let you handle this @duncangraham . Lets change it ti Argo Bus instead of Argo Meteor

**Comment by duncangraham** [comment]
took only a second to change– what was blocking you from doing it @markstm17? 

<img width="1390" alt="screen shot 2015-10-01 at 5 42 57 pm" src="https://cloud.githubusercontent.com/assets/865298/10237254/e2c1e216-6863-11e5-89fb-2a41295adc0b.png">
