### ISSUE TITLE
Create Trip Field/Option Gone

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#148]
I created our first trip this past weekend from Rookies with one email and the one from Milwaukee with another email. For new users it gave the ability and option to create a new trip, but it currently looks like there is no current way for me to create another trip. 

![screen shot 2015-08-24 at 5 02 10 pm](https://cloud.githubusercontent.com/assets/11848699/9453803/8c0da1a2-4a82-11e5-9343-52fa4e63180a.png)

**Comment by duncangraham** [comment]
right, and this will be the case until we decide people should be able to make their own trips.

for now, lets be the only creators so we can work out the bugs.
