### ISSUE TITLE
Organizer Role

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#149]
Now that we have distinguished two roles (admin and user) and you've made both of us Admin and everyone else users, the next focus should be the organizer role (as I/we continue to both be the organizers and administrators in the meantime)

We will be able to continue to work with and do "public buses" like Buffett, either through me, you or starting to work with bars or starting points/pick up locations at these bars, but there is a lot more marketing that goes into that then people coming to us with a specific need that they have for their specific event (or a bar using ArgoBus and advertising at their bar, on their televisions, etc...)

These bars will eventually be the "Organizers" and we will give them a specific Org ID number associated with Argo. ***(Lets call this Org ID our BarCode).*** 

From there these Organizers that are registered with us can create their own trips and can organize trips at their own convenience through Argo instead of traditional means. (Right now, you or me still need to approve these trips ***Because of the cost standpoint*** but once they are approved the organizer just needs to share the link to get users/friends/bar customers to pledge to go from potential trip to real trip)

In future based upon past trips/data/information about trip/mileage/time rented/etc we won't need to approve of these trips for the organizers, it will be programmed (as you have said)

**Comment by duncangraham** [comment]
I have a different idea of the priorities and timeline. lets sync on skype.

**Comment by duncangraham** [comment]
this is stale
