### ISSUE TITLE
Past and Upcoming Trips for Users/Customers

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#15]
Having the ability to see past trips you went on and the trips that you are currently signed up for from the user perspective

**Comment by markstm17** [comment]
![11753822_10154023078147598_1454912963_n](https://cloud.githubusercontent.com/assets/11848699/8686763/c8749ee2-2a4e-11e5-972d-60fe870168f7.jpg)



Past Trips

**Comment by markstm17** [comment]
![11759031_10154023077522598_360953440_n](https://cloud.githubusercontent.com/assets/11848699/8686771/d47aeeda-2a4e-11e5-9c44-a3a4cbc28062.jpg)


Live Trips (Upcoming Trips)

**Comment by duncangraham** [comment]
this is related to and kind of a dupe of #225 

closing
