### ISSUE TITLE
Delete Bus Option

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#152]
this needs to be a thing

**Comment by markstm17** [comment]
This definitely does need to be a thing. We need to give the organizer the ability to do this. But we also need to consider the reasons behind it, and have this process be something that organizers DON'T WANT TO DO after they have gone through organizing, proposing and sharing link for group/users to pledge through. 

But it does need to be an option.

Penalty for Public Buses @duncangraham ? 


If a bachelor party changes plans and they decide they don't want or need transportation thats life. But if a bar organizes or proposes a trip and then enough people sign up and they delete or cancel it?? 

We have to define this option, but again it must be an option

**Comment by markstm17** [comment]
This has been addresses and answered in #162 and #168

**Comment by markstm17** [comment]
You have recently added this function to the #225 

Going to close this
