### ISSUE TITLE
Stripe token bug

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#156]
we're having issues with our Stripe integration (maybe because of an exposed secret token).

digging into this today, will post updates when I have more information

**Comment by duncangraham** [comment]
just gave myself administrator access. updating the rolled tokens and saving them as environment variables (as per https://github.com/mjhea0/node-stripe-charge/blob/0129b770ada5858eb95a0baee176352767159b29/server/_config.js#L13-L20).

**Comment by duncangraham** [comment]
this fixes the implementation.

1. testing the test keys on my dev environment
2. add public keys on our server
3. test public keys
4. close this ticket

**Comment by duncangraham** [comment]
99% sure this is fixed, but I need to finish #157 so I can create a bus and test. will close once I'm able to test for sure.

**Comment by markstm17** [comment]
How is this looking @duncangraham. I know you said #157 and creating private buses is finished. We should test one this weekend to figure out if Stripe is ready to roll moving forward. 

Side note: There is one individual from Buffett one month ago who somehow did not get charged and I just got a hold of him, so I can update his stuff on Stripe and charge him the $35 whenever Stripe is ready to go.

**Comment by duncangraham** [comment]
you should be able to update stripe now. the error is from the integration with the app, not with stripe itself.

Feel free to make a test bus on production and see if this works-- if it doesn't I'll wrap this up after #165 is wrapped up.

**Comment by markstm17** [comment]
On account of you figuring out what was wrong and us successfully charging the customers that came on the Packers vs Chargers bus on Oct 18th, I'm gonna close this.

Reopen if you think we need to @duncangraham
