### ISSUE TITLE
Create private flow

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#157]
as per chat, private flow will let friends split and equally shared bus (so, no dynamic pricing with large gaps)

**deadline is thursday**

i spent today getting the front end completed, will start on backend tomorrow (in addition to #156 )
I'll likely run into back end bugs while I enhance blade's existing work

![image](https://cloud.githubusercontent.com/assets/865298/9901326/cd105000-5c1b-11e5-9e45-f2fdeaa16f6e.png)

**Comment by duncangraham** [comment]
i also might try out a white screen, since this seems like a ton of green, and whites a bit easier on the eyes.

**Comment by markstm17** [comment]
I touched base with our customer today and told her I'll have an answer for her tomorrow about this if it is ready. If it's not, no big deal, I will collect cash or check for their bus Friday. If it is finished tomorrow then it will give them one day to pay through Argo.

As we texted, talked about and you suggested above, I think it would be good to try different background colors, specifically white with green accents/fonts to see the visuals

**Comment by markstm17** [comment]
I absolutely love the three different levels (Important stuff, clicky buttons and nitty gritty) and the general layout of how you constructed the flow @duncangraham. Ditto to your brief, quarky and fun descriptions throughout the process on this page. Awesome UX stuff there. 

A couple of side notes:

- Limo should be an option 
- What if there are more then 80 people? (I've done 150 people before)
- I think Trip name and Occasion (or event) should be different fields
-Trip Name is: "Duncan and Zain's Hostel Rendezvous"
-Occasion (or event) is: Pub Crawl

**Comment by duncangraham** [comment]
columns that I'm adding to the database:
trip_ride_type
trip_food_drink

removing 
trip_event_description

**Comment by duncangraham** [comment]
Looks like I'm gonna have to create a DB migration for things to start working again. was hoping for a simpler solution, but oh well.

**Comment by duncangraham** [comment]
Scratch that, figured out what was wrong: I'm a dumbass.

I created the the column 'ride_type' in the Trips table, and then called the same column 'trip_ride_type' in the code, which made things get break-y. 

**bugs I noticed and am fixing**
- [ ]  directory _site exists and shouldn't
- [ ] remove all instances of trip.trip_event_description (and the other deleted columns)

for now I'm going to work on getting the private bus form working/adding data to the DB

**Comment by duncangraham** [comment]
## Progress
- we can now create private trips!
- added nod.js for front end form validation (http://casperin.github.io/nod/)

## To Do
- allow organizers to add emails to track who has paid (a nice to have)

**Comment by markstm17** [comment]
We should run a test private trip when you are ready @duncangraham 

Give me the go ahead and I can get friends to pledge for a private trip

**Comment by duncangraham** [comment]
will do. The last thing I need to do is remove the template logic (i.e. dynamic pricing) from private events. Every private event should be split equally between all attendees, or be paid as a lump sum by an individual or company.

**Comment by markstm17** [comment]
How close to done is the template logic being updated @duncangraham ?

As far as splitting the private events, yes and great.  Execute splitting the private events and then the lump sum can be added later. (The only difference is that with a lump sum we **ARE NOT** going to have the multiplier based upon however full the bus gets. We will take 5-10% of every bus organized as lump sums through Argo.)

**Comment by duncangraham** [comment]
just added the code that makes every private trip degrade equally. I'll push the updates live and close this.

Keep things hush hush until we can test. which brings up an important point: 
## you need to be able to test Argo in a development environment

1. we both need to test things
2. we can't have you testing things in the production version
3. I need to walk you through how to use github and how to spin up a local server so you can test the development version or I need to publish to another quality assurance (QA) server that runs development code so you can test things before I push them to production.

**Comment by duncangraham** [comment]
app is updated, though there may be bugs.

**Comment by markstm17** [comment]
Opening this simply because of this question. Please answer and close when you get this notification.

Does the private flow have a password for the pledges to input to get accepted for the private bus? 
- If not, how do we distinguish the two different flows and types of trips?

**Comment by duncangraham** [comment]
No password. The private buses won't show up anywhere on the site. You'll only be able to access them if you have the link.

In the future we can add other ways to make things more private (like a way for organizers to remove passengers), but for now it's not an issue.
