### ISSUE TITLE
Charter Product: questions for First Student

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#163]
## Master List

(edit this comment and add questons to the master list. Trev will get answers to these tomorrow.)

![image](https://cloud.githubusercontent.com/assets/11848699/10012477/f9a147f8-60cd-11e5-8701-50bb79ff7ca2.png)

**Comment by markstm17** [comment]
@duncangraham 

I can edit this tomorrow after I get the answers from them, I know this is kind of sloppy, but I just finished typing all of it up on a word document I'm going to use tomorrow. Please throw in any other questions you may want to add for me to ask before you hit the hay if you're up. 

![image](https://cloud.githubusercontent.com/assets/11848699/10012498/34bb95fa-60ce-11e5-8416-759cdc0bd2d9.png)

**Comment by duncangraham** [comment]
## strategy
you probably already have this figured out, but here it is anyway

I'd lead with the 'past customer' => 'future partner' angle. Then I'd give an update on Argo's progress. I'd then say we're in the process of developing the vendor/charter application. This product will give charter companies the platform to be paired with customer demand. If we're successful, the revenue brought to charter companies will be about $40K a month by the end of the year. (~50 buses a month with an average cost of $750 per bus). When we scale the sales team this number will grow dramatically.

Their input at this time will help in the development of the vendor product, benefitting us both.

## It'd have been nice if you had posted the actual text, so I could have written edits.

- could you provide any charter booking data? (does this include school district contract?)
  - total buses booked in 2015? (partial if not total)
  - buses booked per month in biggest markets

## more questions

- whats the size of your fleet? biggest markets? (so we can expand into those cities, providing you with more business)
- whats percentage of your fleet is booked each month? (we can use this as a metric to track how we're helping you grow your business)
- whats the supply of drivers? 
- What markets have the most drivers?
- Are any markets underserved? (Uber has 30K drivers in SF alone. Argo could provide work/jobs in underserved markets)

**Comment by markstm17** [comment]
Going to close this for now @duncangraham. May reopen after I hear back from First Student, or create a more effective ticket for us instead of this piss poor screen shot, when the time is right or when we need it
