### ISSUE TITLE
App-wide form validation

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#165]
I added nod.js in #157. Now I need to implement it across the site so no form is submitted in error.

- [x] create trip page (completed 9/24)
- [x] log in page (9/24)
- [x] sign up page (9/24)
- [ ] edit trip page
- [ ] account details page
- [x] the pledge flow

don't think I missed anything

**Comment by markstm17** [comment]
How close is this to be done and wrapped up @duncangraham ?

**Comment by duncangraham** [comment]
the important ones are done, and the ones remaining will most likely change a bit as things get redone. closing.
