### ISSUE TITLE
Create a User Terms of Service Document

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#168]
Decided to break up our FAQ #162 and TOS tickets that you originally posted

**Comment by markstm17** [comment]
Decided to break up our FAQ #162 and TOS tickets that you originally posted

**Comment by markstm17** [comment]
here are some cool resources I found when I googled 'startup terms of service'

http://techcrunch.com/2012/04/13/snapterms-terms-of-service-as-a-service/
https://www.quora.com/How-does-a-web-based-startup-usually-prepare-or-write-Privacy-Policy-and-Terms-of-Service
reading them, it seems like we should bring an outside advisor (most likely a lawyer) in to help draft this, and the privacy policy.

**Comment by markstm17** [comment]
Last change from FAQ #162 @duncangraham 

as always, Mapbox's terms are great: https://www.mapbox.com/tos/

as is their privacy policy: https://www.mapbox.com/privacy/

Could you add a link to the bus company's TOS as well @markstm17?

We'll likely have a different set of terms for passengers, organizers, and charters.

**Comment by markstm17** [comment]
# Terms of Service for Argo

**Pledging Process and Fares Policy**
- All pledges are provided with round trip (or one way) transportation for vehicle type (motor coach, school bus, "party bus", limo, etc...) listed in specific trip/itinerary details of your public or private event
- Pledge Process is as follows:
 - Absolutely NO RISK to pledge for a Pending Trip if you want to go
 - When Pending trip's threshold is hit, it makes the trip Live. As someone who has pledged, you can "unpledge" at any point until 5 days before event. If you unpledge, there will be a nominal $.99 fee
 - 5 days before event, you are locked in. Get ready for the wheels to go round and round!
 - NOBODY pays or is charged until the time the bus leaves. It gives the group until the last minute to fill seats if they are still vacant, resulting in a lower ticket price for everyone going!
- The pledging process can ONLY be done through link provided from Organizer (whether public or private). No Cash or Checks are accepted 
- Each Argo Bus will depart at whatever time the organizer decided for your specific trips information (whether it's a public or private bus). It is the pledge's responsibility to be at the pick up location at the designated time. Under no circumstances will Argo Bus be responsible or liable for any pledge that does not board the bus (whether public or private) before the departure. 
 - Odds are if it's a private bus, your friends will wait around and give you quite a hard time for being late (no guarantee though), but if it's a public bus and you're late you'll probably be left behind. In either case, liability and responsibility falls on the pledge.
- Argo Bus' mission is to make it effortless and easy for anyone, anywhere to organize and pledge for any trip (public or private) through Argo. Our rates are the most competitive rates, and that's because it is 100% based upon however many people decide to pledge and come (whether it is a private or a public bus). The more filled the bus is, the cheaper your ticket gets. 
 - Costs of groups renting different types of vehicles (motor coaches, school buses, "party buses", limos, etc...) through Argo will vary, thus resulting in a potential increased or decreased cost per pledge with different Argo trips using different vehicles
 - Trip details organized by the groups organizer or any particular group outing using Argo will vary from group to group, resulting in different costs. Costs to rent any of these vehicles largely depends on rental time, distance traveled, amenities, parking passes, clean up fees, etc...
 - Lastly, costs may vary based upon departure city and destination
 - All pledges will constantly be eligible for discounts as the bus continuously gets filled, up until departure time for any Argo trip.  
 - Final "Cost Per Pledge" may be subject to additional charges; largely based upon if vehicle is trashed, or rental time exceeds original trip itinerary details
- A valid photo I.D. is needed to board for every single public bus. A valid photo I.D. is NOT needed for any private bus, but you should probably have one on you anyways

**Cancelation Policy for Argo Organizers**
- Public Bus Organizers reserve the right to cancel or modify any pending trip's itinerary at its sole discretion. Any live trip where the threshold has been hit by having enough pledges will not be able to be canceled by the organizer. Argo and it's public event organizers will provide advance notice of any cancelation of a pending trip and any modification of a live trip.
- Argo will not be responsible for delays caused by breakdowns, accidents, road conditions, weather and any other conditions beyond our vendors/partners control, including strikes, or cancellation due to not hitting pledge threshold for a particular pending trip. 
- Argo does not guarantee that an organizer using our Argo platform does or doesn't change pick up or drop off locations and times
- Argo utilizes third party vendors and Argo partners only with third party vendors that have the same goals and visions that we have in mind; mitigating financial risk for their customers (our organizers) and saving all of our pledges money. Argo does reserve the right to change third party vendors and operators at any time

- Private Bus Organizers reserve the right to cancel or modify any pending or live trip's itinerary at it's sole discretion. 
- If the organizer for a private trip decides to cancel a live trip after the threshold has been hit, we require a written explanation of why he or she has decided to cancel. 

**Third Party Events**
- As an additional service, Argo sometimes offers tickets to events that public or private buses are going too through our website. These event tickets are offered directly through a third-party or venue and additional fees, including any transaction fees may be associated with this purchase
- Argo is not responsible for cancelations, delays and/or postponements due to weather conditions or any other circumstance.

**Minors and Passengers under the Legal Drinking Age (21)**
- The minimum age to ride an Argo Bus is thirteen (13). Proof of age and an additional parental release may be required.
- Using a credit or debit card to reserve for minors under the age of eighteen (18), is deemed as the cardholder giving consent to travel with Argo Bus (whether public or private) under all the terms herein.
- If it is determined that at any point in time, before during or after, that any minor(s) or underage pledger(s) possess or have consumed alcohol or any illegal substance, Argo Bus reserves the right to remove such passengers and a parent or a guardian will be required to pick up the minor
- Under no circumstance does Argo hold any liability for underage consumption or possession of alcohol or consumption or possession any other illegal substances or the removal of pledges who have violated the above rules, on its vendor charter buses.

**Pledge Conduct, Personal Property and Miscellaneous Rules**
- _For every Argo bus there will be a small security deposit ($100) that will be spread out amongst the entire group of pledges. Upon final drop off, the driver will determine if the bus was left in satisfactory condition. If the entire bus was left with trash, was messy, one or multiple people vomited or it was left unsatisfactory in any way, nobody will receive their portion of their security deposit refund 
 - If 20 people were on the bus Argo will credit back $5 to each individual, if 50 people were on the bus, then we will credit back $2 per person._ 
- Pledges are liable for any damage or clean up fees caused by his or her actions including but not limited to damage of windows, seats, audio visual equipment and lavatories. 
- Argo is not liable for any personal injuries caused by any other pledges negligence or recklessness towards himself, herself or others
- Argo's vendors/partners and charter vehicles are not responsible for any lost, stolen, or damaged items or baggage left on the vehicle or brought onto or off of the vehicle. 
- Pledges are responsible for placing bags, coolers, chairs, and other retrievables into the baggage bins, underneaths their seats, or in the proper area on each type of bus/vehicle and retrieving it at their destination. 
- Argo does not allow transportation of weapons of any kind or any material that would be classified by the Department of Transportation (DOT) as a hazardous material (Acids, ammunition, explosives, firearms, or all types of fireworks, flammable liquids, hazardous materials, poisons, radioactive materials, etc..)
- If a pledge mistakenly leaves a possession on their bus, Argo will do everything possible to reconnect with the service location and the driver to reclaim their possession which may be in their lost and found at their specific location.
- Smoking is prohibited aboard the bus, in accordance with State and Federal regulations. 
- Dogs, cats, birds or other animals will not be transported. A service animal will be permitted to travel with a pledge at no additional charge
- Not all vehicles through Argo are wheelchair accessible. Please contact Argo for specific information regarding accessibility. 
- Alcohol consumption is permitted on most buses/vehicles, unless otherwise noted. Under no circumstances is underage consumption of alcohol permitted by Argo buses/vehicles. Argo reserves the right to remove passengers who do not comply with underage drinking regulations. 
- Argo reserves the right to refuse transportation services to any pledge who is under the influence of drugs or alcohol who poses a threat or danger to any other pledges or people riding any particular bus. Argo also reserves the right to refuse transportation for pledges who refuse to permit a search of his or her person, personal belongings or property for weapons, who fails to provide a valid photo I.D. upon request, or who refuses to comply with any lawful rule or regulation. Such pledges may be removed from the bus, along route, without any liability to Argo's vendor/partner and charter vehicle. No refund will be issued to any pledge that gets removed for any of these reasons
- Argo reserves full control and discretion to assign or change the seating of any pledges at any time, during the trip, for any lawful reason. 

##### These terms and conditions may be changed at any time at our sole discretion, without prior notice

**Comment by duncangraham** [comment]
next actions are on me. I'll provide any edits and get these uploaded and linked on the site.

**Comment by duncangraham** [comment]
added. closing this.
