### ISSUE TITLE
Charter Terms and Conditions Example (First Student)

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#169]
I'm breaking up FAQ #162 again.

I posted screen shots of the terms and conditions I get every time I rent a bus from First Student. This is completely different issue and should have it's own ticket then #162 and #168

**Comment by markstm17** [comment]
This is the Terms and Conditions for First Student after booking a bus

I also emailed you the PDF. Here are screen shots of First Student as the example

**Comment by markstm17** [comment]
![image](https://cloud.githubusercontent.com/assets/11848699/10109682/1512e43e-638e-11e5-84f2-91d7e7e37ba4.png)

**Comment by markstm17** [comment]
![image](https://cloud.githubusercontent.com/assets/11848699/10109695/2a1e2e4c-638e-11e5-949a-860d4795c120.png)

**Comment by markstm17** [comment]
![image](https://cloud.githubusercontent.com/assets/11848699/10109702/3a5b3714-638e-11e5-9635-b6e648c00f4a.png)

**Comment by markstm17** [comment]
![image](https://cloud.githubusercontent.com/assets/11848699/10109708/4c49f992-638e-11e5-8631-9cb967e67420.png)

**Comment by duncangraham** [comment]
this was related to #173 and #168 which happened
