### ISSUE TITLE
Create Social Media Profiles 

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#170]
@duncangraham I have already created the following accounts:

**Facebook**
- Argo Bus
- Argo

**Instagram**
- Argo_Bus

**Twitter**
- @argo_bus (Argo Bus)

Let me know when/how you want me to post the passwords and how to proceed from here.

**Comment by duncangraham** [comment]
wanna link the accounts? 

we used meldium (https://www.meldium.com/) at mapbox for this type of stuff. feel free to take point on this and decide what login manager we should use.

**Comment by markstm17** [comment]
Alright just set up a meldium account:

Log in: Calibadgerllc@gmail.com
password is: Trevorandduncan2015

My Account: Argo
Name: Argonauts

**Comment by markstm17** [comment]
Whats the best way to link the different social media accounts through Meldium @duncangraham since you've used it before. It doesn't communicate and explain how very effectively. 

I'll keep playing around with it and I'm sure I will probably figure it out

**Comment by duncangraham** [comment]
can you move this to the business repo @markstm17? Lets try to keep this repo focused on product development.
