### ISSUE TITLE
add TOS check to pledging flow

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#173]
Argoers should check that they've read and agree to the TOS.

**Comment by markstm17** [comment]
Awesome. Obviously read through what I posted on #168 for the TOS. Any changes or edits you want to make or suggest please post here so I'm up to speed with what you have changed @duncangraham

**Comment by duncangraham** [comment]
<img width="1390" alt="screen shot 2015-10-04 at 11 50 47 am" src="https://cloud.githubusercontent.com/assets/865298/10269495/32b917cc-6a8e-11e5-82c0-66f2adcc6ce1.png">

shipped.
