### ISSUE TITLE
TEST: Can I book 2 trips and be charged for both

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#176]
background in #174. 

next steps: @markstm17 tests whether he can book multiple trips and be charged on both.

**Comment by markstm17** [comment]
# Just went through this with our two current "Test trips" and here are the results @duncangraham 

![screen shot 2015-10-21 at 11 49 13 am](https://cloud.githubusercontent.com/assets/11848699/10643699/d91c8852-77e9-11e5-9d3d-41cc11c4b26a.png)

I signed up for this trip first and it said that I was signed up UNITL
--
![screen shot 2015-10-21 at 11 48 53 am](https://cloud.githubusercontent.com/assets/11848699/10643719/f36d385a-77e9-11e5-9e98-02da1e7b57f8.png)

I signed up for this trip 

--


As you can see this is what I was referring to in where the Current passenger number does not match the
