### ISSUE TITLE
 Implement Send Grid account

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#183]
background in #137

**Comment by markstm17** [comment]
This happened and is now accessible and updated through Meldium

**Comment by markstm17** [comment]
# Email from SendGrid Support 

> Hi ArgoBus,

> Thanks for your interest in SendGrid, looks like we need you to address the following:

--------

> We’d like to know a little more about the email you’ll be sending through SendGrid. Please elaborate on the following:

> 1. The nature of your business, the services you provide, and your potential customer base
> 2. Your sending frequency and volume
> 3. How you collect your recipient addresses
> 4. How you will allow your recipients to opt out of your emails (whether you plan to use SendGrid’s one-click unsubscribe feature, or if you have your own method)
> 5. The types of messages you will be sending (transactional or marketing)

> Please reply at your earliest convenience in order to continue the provisioning process. Thanks for your cooperation!

# My Response 

> 1. ArgoBus is a group organization tool for the customers of charter bus/motor coach/limo companies that deal with the pains and headaches of getting groups of people to commit and prepay. These charter companies are used for various events; both public and private. They include sporting events, concerts, weddings, bachelor/bachelorette parties, tours, conferences, etc... Our potential customers are the organizers of these social or professional events.

> 2. We are a startup, so right now we anticipate far less then 12,000 emails a month

> 3. We collect our recipient addresses through them giving us their email addresses when signing up through our site.

> 4. We are most likely creating our own method, but may try the one click unsubscribe feature

> 5. Both transactional and marketing. Transactional in the fact that eventually (when the bus leaves), our customers will be charged a fee that covers the cost of the rental charter bus based upon however many people are on the bus. Marketing in the fact that it will update users who have pledged and committed to a bus when their price decreases when more and more people sign up and commit to that particular bus.

> Let me know if you have any more questions

> Trevor Marks

# Current Status

> Thanks for contacting SendGrid's Support team!

> We've received your request, and we're diligently working 24/7 to address your issue. We're currently experiencing a high volume of inquiries. We will certainly help you out as soon as we can.

> To check the status of the ticket and add additional comments, follow the link here support.sendgrid.com/hc/requests/516432, or you can also update this ticket by responding directly to this email.

> Thanks for your patience!

**Comment by markstm17** [comment]
Closing for now, should be accepted in the next 24 hours from SendGrid

**Comment by duncangraham** [comment]
reopening for continuity.

Changing name to: Implement Send Grid account.

Next actions are on me.

**Comment by duncangraham** [comment]
this happened.
