### ISSUE TITLE
New trip email to admin not working

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#186]
I just created two new trips, one public and one private

Good news is: 
- For the private trip there is nowhere to search for it (which we want)

But:
- It did not give me a link to share with my friends, so how does anybody pledge?
 - Side not is that it says I have not gone on any trips yet, even though I did

![screen shot 2015-10-02 at 1 41 02 pm](https://cloud.githubusercontent.com/assets/11848699/10254938/6932937e-690c-11e5-8f36-737a237b8057.png)

--

For the public bus:
- Here is the screen shot
- I did not receive an email to allow me to approve of the trip

![screen shot 2015-10-02 at 1 43 18 pm](https://cloud.githubusercontent.com/assets/11848699/10254944/74650826-690c-11e5-8c63-4c07193a9d52.png)

# The function for us as "administrators" to approve of these trips is NOT working

**Comment by markstm17** [comment]
I just put together a Packers vs Chargers trip that I'm going to organize @duncangraham 

Don't have access to it because of the above ticket situation

**Comment by duncangraham** [comment]
i can still access the /admin endpoint, and after chatting it sounds like this is only and email issue.

renaming the ticket and searching for the bug. this will also be a good time to do #183

**Comment by duncangraham** [comment]
Well, this is dumb.

There's no sendgrid integration on production https://github.com/ArgoBus/Argo-Project-V0/blob/219bcd45a3ee74eaba7695969817e143ee4cf079/routes/email.js#L5-L6, so obviously emails wouldn't be working. fixing.

**Comment by duncangraham** [comment]
:ship: ed
