### ISSUE TITLE
Birthday Field required when pledge inputs their Credit Card information for their first trip through Argo

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#188]
This will give us the information we need as we build the incentive portion on the growth-user acquisition repo for pledges to not have to pay **when we implement free birthday months**

This should be an easy fix and I say adding the birthday field is **high priority.** We need to start getting that information as users sign up ASAP
- I say make it required and for the time being if they try and submit/pledge/input info with it blank, communicate and tell them we need to know when it is, **because in the future we plan on giving birthday specials!**

**Comment by duncangraham** [comment]
Rad. It'll ship today/tomorrow.

**Comment by duncangraham** [comment]
:ship: ed!

<img width="1390" alt="screen shot 2015-10-05 at 12 00 01 am" src="https://cloud.githubusercontent.com/assets/865298/10274580/1e3a3c3e-6af4-11e5-9200-6eb3b15baf78.png">
