### ISSUE TITLE
update datetimepicker style

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#194]
it looks like garbage now.

<img width="1390" alt="screen shot 2015-10-04 at 12 00 55 pm" src="https://cloud.githubusercontent.com/assets/865298/10269526/955ea0a8-6a8f-11e5-8cd6-a9180decde1f.png">

**Comment by markstm17** [comment]
Yeah agreed, this definitely needs to be updated 

# Also 
- For the minutes have increments of every 15 minutes 
 - Nobody cares or gets picked up at 4:08pm for example. It should be 15 minute increments

**Comment by duncangraham** [comment]
![step](https://cloud.githubusercontent.com/assets/865298/10561410/47e99fd8-74dc-11e5-83db-7f3fa47cf143.gif)

the datepickers now move in 15 minute increments

**Comment by duncangraham** [comment]
<img width="1392" alt="screen shot 2015-10-17 at 2 48 27 pm" src="https://cloud.githubusercontent.com/assets/865298/10561456/29808b2c-74de-11e5-8e2f-81aac34d8efe.png">
<img width="1392" alt="screen shot 2015-10-17 at 2 48 31 pm" src="https://cloud.githubusercontent.com/assets/865298/10561455/297fb49a-74de-11e5-8918-493f236c46bd.png">


this is done and will ship in the next release.
