### ISSUE TITLE
Change "checked mark" details to the Argo Green to make more visible 

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#198]
After an organizer fills out the trip details, to better stand out and to brand the Argo green, it should change the font to the Argo green on this page. 
- Low priority right now, but just thought of it as I put together the Packers vs Chargers bus 

![screen shot 2015-10-05 at 11 11 45 am](https://cloud.githubusercontent.com/assets/11848699/10286182/1f598ed6-6b52-11e5-959e-97ff3f1c1a34.png)

So:
- Public
- Motor Coach
- Medium: 25-50 people
- Food and Drink

Should all be the Argo green

**Comment by duncangraham** [comment]
<img width="1390" alt="screen shot 2015-10-05 at 9 38 58 am" src="https://cloud.githubusercontent.com/assets/865298/10287024/b10f4a94-6b45-11e5-9f0e-6c123e3138fe.png">


I agree that it could be more legible, but I don't think this looks good. I'll work with some other options.

**Comment by duncangraham** [comment]
<img width="1390" alt="screen shot 2015-10-05 at 9 46 53 am" src="https://cloud.githubusercontent.com/assets/865298/10287097/0a3fd0f2-6b46-11e5-87b8-bdfa4e1a3d01.png">


made some changes to positioning, border color, and text color. Closing the ticket. This will ship with the next larger deploy.
