### ISSUE TITLE
Trevor doesn't have access to Argo Admin Page

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#200]
After trying to go to the admin page to approve the Packers vs Chargers game I organized so I can start texting friends and people to get them to pledge, it displayed this saying I don't have access to it. 

Wanna walk me through how I can, OR give me access at some point today Dunc?

![screen shot 2015-10-05 at 1 59 19 pm](https://cloud.githubusercontent.com/assets/11848699/10290400/6f0bd01c-6b69-11e5-9506-a0b7ffe91cab.png)

**Comment by duncangraham** [comment]
<img width="1274" alt="screen shot 2015-10-05 at 12 25 02 pm" src="https://cloud.githubusercontent.com/assets/865298/10291008/44f4b6e8-6b5c-11e5-990e-319a53b516dd.png">


your markstm17@gmail.com address has admin access. not sure what's happening here.

**Comment by duncangraham** [comment]
@markstm17 wasn't signed in. closing.
