### ISSUE TITLE
Change Make Reservation to Pledge 

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#201]
Low priority right now, might have posted on some other ticket actually

We need to start branding with our "pledge concept". 
- We've got to think in terms of adding "pledge" to people's and users vocabulary when talking about Argo, just as Facebook has done with "Like" when people are talking about pictures and posts on Facebook.

![screen shot 2015-10-05 at 3 09 25 pm](https://cloud.githubusercontent.com/assets/11848699/10292439/dffb4f0e-6b74-11e5-9019-b007e6645494.png)

**Comment by duncangraham** [comment]
this happened
