### ISSUE TITLE
Stripe Automatic Transfers Now back Up to Date

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#203]
Just updating you about my conversation with Anjali from GitHub earlier today. It's finally up to date so we can have automatic transfers again.

> Hi Trevor,

> Thanks so much for making the time to speak with me just now! We've restored your account fully so your Stripe transfers should go through automatically without any further issues, but if you encounter any problems, please let me know.

> As I mentioned on the phone, unauthorized API key access is usually tied to accidentally publishing one's API keys in a public space like a public GitHub repository. To ensure your account stays secure in the future, you may want to double check with your CTO that your Github repo has been cleaned up. If either of you has any questions about that, feel free to send me an email and I'm happy to follow up further.

> Best regards,

> Anjali

We good with the repo and our API keys correct @duncangraham?? She asked me to make sure they weren't public anymore. 

Close after your read and give me the thumbs up.

**Comment by duncangraham** [comment]
They were never public, so I'm not sure what happened. That said, everything should be tidied up to stripes liking.

closing.
