### ISSUE TITLE
Necessities from Duncan for pitching to bars to organize through Argo

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#207]
#189 Covers most of it

More specific and referencing the specific tickets include:
#135 
#167 
#190 
#205

**Comment by markstm17** [comment]
Let me know if you want more specifics @duncangraham 

I need a real flow of screen shots of the process and the ability to walk bar managers and owners through our system to show how easy it is, with ALL THESE VISUALS from the organizers perspective as well as how and why their customers will want to sign up at their bar

**Comment by duncangraham** [comment]
@markstm17 is this relevant for this repo? or relevant anymore period? What are the next actions? if it's stale feel free to close it.

**Comment by markstm17** [comment]
Closing. Far along enough to start showing argobus.com !! 

WOOHOO
