### ISSUE TITLE
Need to make First and Last name part of CC payment process page (Null Null problem)

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#208]
We have received a lot of null, null's again. The majority of people don't input their name in their personal info spot when they are signing up for a bus. Below is a screen shot of 6 out of 8 people inputting their names, with me being one of them 

![12166994_10154262108492598_380072583_n](https://cloud.githubusercontent.com/assets/11848699/10504008/778db26e-72c1-11e5-8e22-4c8903301b92.jpg)

**Comment by markstm17** [comment]
As you can see, Chrissy and Brandon only put their first names too. We need first and last names

**Comment by markstm17** [comment]
# Hope this provides you with good feedback Dunc

#### Below are the users comments for this issue:


![11696657_10154262130197598_587650553_n](https://cloud.githubusercontent.com/assets/11848699/10504346/34a1b35c-72c5-11e5-952a-59475873fd74.jpg)

--

![12166267_10154262130852598_964535285_n](https://cloud.githubusercontent.com/assets/11848699/10504347/3c007d0e-72c5-11e5-8e02-b439360ca082.jpg)

**Comment by duncangraham** [comment]
uhh..... wtf?

<img width="1277" alt="screen shot 2015-10-15 at 3 29 41 pm" src="https://cloud.githubusercontent.com/assets/865298/10529306/9af37d34-7351-11e5-91a7-f3bac01b5442.png">

im not sure how people are incorrectly doing it- the form wont submit without first and last names

**Comment by duncangraham** [comment]
figured out this was due to an incorrectly configured stripe account. close when you feel like it trev
