### ISSUE TITLE
Seeing how many people have pledged from users experience/standpoint

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#209]
This was a text a I received today from a user wondering how many people had signed up. 

_Should_ should say **showed**

![12167353_10154262129497598_939317113_n](https://cloud.githubusercontent.com/assets/11848699/10504302/98b67b12-72c4-11e5-9dff-183ce2fe672e.jpg)

**Comment by duncangraham** [comment]
this happens on the page after you've pledged. I can do the trip details page too.

if that's the case, I need to add privacy options

**Comment by markstm17** [comment]
Yeah there is no way to go back to see who has joined or pledged since you pledged though. Whether it is a private or public event on Facebook, people can ** GO BACK** and see others who have joined after they have.

That is what he was referring to, being able to see who has pledged after he (or she) has

What we are building is a social (offline, in real life though!) experience. People want to know that there friends are going, or who is going, etc... (Whether it is a public or private event)
- Just cuz it's public doesn't mean that people won't know each other, there are obviously sub groups to make the overall group, and people want to go back and see who has pledged for two reasons:
 - To see if ALL of their friends have pledged 
 - To see if they know anyone or know friends of friends on the bus
  - The girl you talked to today (Traci) saw through the Argo Bus Facebook event that I'm friends with one of her best friends and I've never met that Traci before. People like that and it creates conversation and something to talk about on the bus outside of the event and reason for the bus itself.

**Comment by markstm17** [comment]
Just communicating with you @duncangraham that Argo needs to communicate who and who has not signed up for the sub groups of people that plan on going/are pledging

This should be automated and communicated within the app/website, not from our standpoint as admins that need to communicate this behind the scenes 

![12167020_10154267102262598_868489831_n](https://cloud.githubusercontent.com/assets/11848699/10560447/46a5d5ac-74d1-11e5-9588-52e9e5d61c7c.jpg)

**Comment by duncangraham** [comment]
this was shipped, though there are some hiccups currently
