### ISSUE TITLE
Better error states on /login

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#215]
This is done, I just wanted to log it so you saw @markstm17 

### currently this is what happens on error
<img width="1391" alt="screen shot 2015-10-16 at 12 04 35 pm" src="https://cloud.githubusercontent.com/assets/865298/10550848/24c2eb7e-73fe-11e5-804b-f07224d9da24.png">

### the fix
<img width="1391" alt="screen shot 2015-10-16 at 12 05 20 pm" src="https://cloud.githubusercontent.com/assets/865298/10550852/30805e56-73fe-11e5-9eda-991e43650aa5.png">

For now, this works. later I'm sure it can be optimized further.

feel free to close whenever

**Comment by markstm17** [comment]
This is perfect for now @duncangraham 

Great work
