### ISSUE TITLE
change price estimate to range

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#216]
this happened, just logging so you know @markstm17 

**background**: https://github.com/ArgoBus/Argo-Project-V0/issues/189#issuecomment-148510606

# old
flat, full price

# new
<img width="1391" alt="screen shot 2015-10-16 at 12 37 59 pm" src="https://cloud.githubusercontent.com/assets/865298/10551621/cd514b92-7402-11e5-8c25-f362f015a866.png">

close when you've seen this

**Comment by markstm17** [comment]
Rad dude. Great work @duncangraham
