### ISSUE TITLE
Argo doesn't need to Approve Trips

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#217]
# current email

![12166818_10154267101962598_1576902094_n](https://cloud.githubusercontent.com/assets/11848699/10560490/13daf714-74d2-11e5-99ef-5deaffc37a44.jpg)

--

# should say and effectively communicate the following

- This trip will automatically go from a potential bus to a booked bus when it is at 40% capacity
- We need to hit the 40% capacity threshold at a minimum of 7 days before your event (instead of saying 7 days, have it say October 14th if the trip is October 21st) 

# visual and sharing
- Here is the link to share with your customers
- This price-o-meter can be displayed on your televisions to visually communicate where the status of this bus is for your customers

**Comment by duncangraham** [comment]
I'm unclear what the intent of this ticket is, but I think it's :+1: to close it

**Comment by markstm17** [comment]
All I meant was when a trip (public or private) is requested or made through "Create a Trip" it should be ready for users to start pledging to. 

We (Argo) need to get notified to get bus quote ready for us on backend (and in future it'll go to bus company themselves).

Good to close, I'm pretty sure you fixed this
