### ISSUE TITLE
Argo doesn't need to approve Private trips 

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#221]
Same as #217 

except that it is based on the Threshold that the organizer for the private bus inputs

**Comment by markstm17** [comment]
# should say and effectively communicate the following

- This trip will automatically go from a potential bus to a booked bus when it **Hits YOUR THRESHOLD OF X**
- **YOUR GROUP** needs to hit **YOUR** threshold at a minimum of 7 days before your event (instead of saying 7 days, have it say October 14th if the trip is October 21st) 

# visual and sharing
- Here is the link to share with your **Friends, family or group**
- This price-o-meter displays **what the cost per person is at different capacities for your private event**

**Comment by duncangraham** [comment]
pretty sure this happened
