### ISSUE TITLE
Three Different Options

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#234]
## To recap, three different options include:

- [x] **Public buses**
- Can be at a Bar, Intermodal station, park and ride, public union, ANY public meeting spot, etc...
- Threshold is hit at 40% capacity
- Our multiplier is currently 1.2 of the total bus cost **($500 bus is actually $600 through Argo)**
- Price breaks at the following capacities:
 - 50%
 - 75%
 - 100%
- ArgoBus has control behind scenes over the thresholds for these public buses and cost per pledge is solely based upon the amount of pledges that sign up for event
- Automated like @duncangraham envisions it and has said time after time
- [x] **Private buses**
- Currently also have a 1.2 multiplier (which is completely fine for now, but will change as we continue to grow because we don't want to leave money on the table) 
- Very simple: Every time someone signs up, it gets cheaper and cheaper and cheaper. 
- [ ] **Private buses (Lump Sum)**
- Organizers that use Argo Bus that **want to pay for the entire thing themselves** and simply UTILIZE the pledging process for their group to gauge who is coming AND to benefit through a FREE PUBLIC BUS TICKET for a FUTURE event

**Comment by markstm17** [comment]
@duncangraham 

Once the three different options are available and completed through argobus, then check them and lets close this! 

Also #235 is just a ticket to start to stir up conversation about other ways to gets people to use Argobus in the future. 
- All four examples happen all the time and the beauty of it is they have their built in communities and groups of people that go on buses to whatever social or professional functions are happening

**Comment by duncangraham** [comment]
I'm closing this in favor of a more directed ticket
