### ISSUE TITLE
Public Bus Option: Delete stretch limo AND make 50 passenger "school bus" template

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#248]
We just talked about this @duncangraham 

For private buses the user/organizer can request a range of small group, medium group or large group.

![screen shot 2015-11-12 at 11 35 16 am](https://cloud.githubusercontent.com/assets/11848699/11128469/96301d44-893f-11e5-9db6-d102be449ea5.png)
--

For the "public buses" we've got the 56 passenger coach bus template through the dynamic pricing. WOOHOO!

For now lets delete "stretch limo" as an option 

AND

**Not mandatory or essential now** Let's make a 50 passenger public "school bus" template (max seats for certain school buses)

Current screenshot of public buses

![screen shot 2015-11-12 at 11 35 04 am](https://cloud.githubusercontent.com/assets/11848699/11128564/231f0620-8940-11e5-9e4d-2c6d81aa4448.png)

**Comment by duncangraham** [comment]
Could you say why we're deleting limo's @markstm17?

**Comment by markstm17** [comment]
The thought process was to originally keep it more simple for us and just deal with larger school buses and motor coaches

**Comment by duncangraham** [comment]
:+1: I commented the button out. We can uncomment and add it back in later

**Comment by markstm17** [comment]
Perfect :+1:
