### ISSUE TITLE
Private Bus has Public Bus Flow

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#249]
![screen shot 2015-11-12 at 4 13 51 pm](https://cloud.githubusercontent.com/assets/11848699/11132941/88f4bfae-8958-11e5-9969-401cff2fe20f.png)

It shouldn't be the public bus flow. every person who signs up should decrease overall cost based upon capacity amount

**Comment by markstm17** [comment]
This should be updated!

Close when it's all good and dandy on your end @duncangraham !

**Comment by duncangraham** [comment]
![screen shot 2015-11-16 at 11 31 25 am](https://cloud.githubusercontent.com/assets/865298/11192351/9747f3be-8c55-11e5-85bc-27a687635f8b.png)

Private bus page has been updated, but the price has a bug that needs fixing
