### ISSUE TITLE
Was, Is, Could Be Function

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#252]
![screen shot 2015-11-13 at 12 14 00 am](https://cloud.githubusercontent.com/assets/11848699/11140024/92cb910e-899b-11e5-8920-fca33dbe13e4.png)

For the above screen shot, I think we should show the following for Public buses:

- What the cost "was"
- What the cost "is"
- What the cost "could be"

This also kind of relates to #244 . I think these two, simple functions will help **communicate** EVEN BETTER THEN WE ALREADY ARE DOING, what Argo really does. 

Thoughts @duncangraham ?

**Comment by markstm17** [comment]
In the above example it would say:

The **current cost is:** In the box- $47      13 more passengers to unlock


AND



The **cost could be at full capacity:** In the box- $18        47 more passengers to unlock

**Comment by duncangraham** [comment]
wanna sketch your ideas with https://precursorapp.com?

**Comment by duncangraham** [comment]
I'm not really sure what you're suggesting here @markstm17. we already communicate was, is, and could be.

reopen if I'm misunderstanding the intent.

<img width="402" alt="screen shot 2015-11-17 at 6 31 17 pm" src="https://cloud.githubusercontent.com/assets/865298/11231019/6b43cae0-8d59-11e5-9f50-e62188e044e2.png">

**Comment by markstm17** [comment]
This communicates my "was, is and could be" idea way better.

Past Price = Was
Current Price in bold = Is
Number of passengers to unlock = Could Be

The above screen shot is primo @duncangraham. Double Thumbs up
