### ISSUE TITLE
Private Bus Flow for Links sent out via text, email, Facebook etc...

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#253]
When somebody is given a link of a private bus to pledge too, they need to do one of two things after clicking the link:
- Sign Up (If first time user)
- Log In (If current user)

With either action, the new user or existing user is taken to the home page where he or she can access public buses

BUT 

no longer has access to the private bus link that was just sent.

**Comment by duncangraham** [comment]
This was fixed
