### ISSUE TITLE
16 new Stripe customers, 22 people signed up, 36/50 Displayed 

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#255]
![screen shot 2015-11-14 at 11 23 32 pm](https://cloud.githubusercontent.com/assets/11848699/11167437/2657d6da-8b27-11e5-9ede-93c3f7e538ed.png)

This relates directly to #247 and the constant inconsistency with the number of people signed up (list of names) to the number of pledges accounted for on the trip (36/50)

**Comment by duncangraham** [comment]
this is a duplicate
