### ISSUE TITLE
Marketing Idea

### ISSUE THREAD

**Issue by TheKingGinger** [ArgoBus/Argo-Project-V0#256]
Hey team, 

I had a random thought pop into my head over the weekend and I think it would be a theme we could market ARGO around that would be playful in a way. I remember as a kid being at the bus stop each morning hanging out, making friends, listening to daily gossip, etc. What if we had a theme for a marketing campaign as an adult bus stop? Also, if you didn't have these experiences as a young whippersnapper then that is a total bummer, but I think a lot of people (our age in particular) could relate.

Thoughts on this up front? Its going to be a goal of mine to have a rough idea by Monday evening and a plan for implementation by the end of the week.

**Comment by duncangraham** [comment]
:+1: yea this could be a nice marketing pitch
