### ISSUE TITLE
user.getTrips not working

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#259]
I cant figure why user.getTrips() isnt working, so I submitting an issue to sequelize. This is what is holding up the Stripe work @markstm17 

https://github.com/sequelize/sequelize/issues/4874

**Comment by duncangraham** [comment]
Fixed this. 

It ended up being a bug caused by my passport-local-sequelize implementation. Now everything is connected properly, but I'm not sure that the existing database will work :-\

If not, I'll go through and populate a new database with the old information

**Comment by markstm17** [comment]
By populating a new database with the information, it should be fine to charge them  for the bus then right @duncangraham ?

**Comment by duncangraham** [comment]
nooooooope. Fixing the ticket count bug. Once that's done I'll charge the trip.

**Comment by markstm17** [comment]
As we talked about @duncangraham, we need to charge the group of 20 people $18 per person MANUALLY instead of charging the group $30 per person to reach $600
- Because it was our screw up with the website and the product and the pledging process
