### ISSUE TITLE
New users cant sign up 

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#262]
![screen shot 2015-11-20 at 11 27 06 pm](https://cloud.githubusercontent.com/assets/11848699/11316870/3f64eecc-8fde-11e5-81b5-ef120fc454c6.png)

Tried signing up as a new user so I could read the Terms and Conditions to see if we put in there that they are "agreeing" to Argo Bus having the ability to take photos and videos of the different trips in the future 

I'm assuming this happened with the latest deploy

**Comment by duncangraham** [comment]
fixed with this commit https://github.com/ArgoBus/Argo-Project-V0/commit/6555343d08de563be28cfdd066a51bd909d3c1c8
