### ISSUE TITLE
Nobody has pledged and there is a "past price"

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#263]
![screen shot 2015-11-21 at 5 35 34 pm](https://cloud.githubusercontent.com/assets/11848699/11321056/6ea422fa-9076-11e5-8f7c-086495709eb1.png)

**Comment by duncangraham** [comment]
fixed with https://github.com/ArgoBus/Argo-Project-V0/commit/454e0f1e5cdce3135ab57dc92c32278815a59e02#diff-2
