### ISSUE TITLE
Implement different user group and more complicated relation

### ISSUE THREAD

**Issue by freindst** [ArgoBus/Argo-Project-V0#43]
Right now, user group has not been implement. It should be completed by add a new field in user model. In addition, alias name is necessary when adding more than one relation between user model and trip model.
Some goals to achieve:
1. - [x]]User can only edit trips created by him.
2. - [  ] Administrator is the only one who can charge passenger and settle down a trip.

**Comment by markstm17** [comment]
This is pretty important to not allow users access to the admin page, especially when people start pledging and filling seats, with real payment info @duncangraham and @freindst 

We either need to be able to change it, or not allow access with this first bus trip for anyone

**Comment by markstm17** [comment]
Going to close this because it's old and outdated now @duncangraham
