### ISSUE TITLE
Experiment transaction with real money

### ISSUE THREAD

**Issue by freindst** [ArgoBus/Argo-Project-V0#47]
We are using sandbox testing payment, so although transaction seems to be completed, there is no real cash flow.
I think @markstm17 can go to https://www.braintreepayments.com/, sign up an account for argobus, and give us the right to control the account. But this is not very urgent, because I feel right now we had better to stay in sandbox until we are sure our project is reliable and secure.

**Comment by duncangraham** [comment]
this happened.
