### ISSUE TITLE
When I put in wrong email/password it directs to unauthorized white screen

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#62]
![screen shot 2015-08-02 at 9 47 04 pm](https://cloud.githubusercontent.com/assets/11848699/9030260/b68d3074-3965-11e5-9233-375536bfe5a1.png)

**Comment by duncangraham** [comment]
yea we should handle this error better.

**Comment by markstm17** [comment]
Sounds good @duncangraham

**Comment by markstm17** [comment]
Last we talked (from this past week with it happening with Traci, whom you talked with over the phone), you said that it was fixed, or handled/communicated better.

Will let you close if it's good to close @duncangraham

**Comment by duncangraham** [comment]
yea this was fixed in #215
