### ISSUE TITLE
A picture for the trip on this page

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#66]
We will delete the test trip (Packers), and will ONLY have Buffett as the option and I'll promote it to my group of friends and people that will be going on the bus

**Comment by duncangraham** [comment]
I think we should pull back here. 

I think the trip should look good, but I think it would be an error in judgement to mimic the eventbrite or other hackathon views. We can do some cool stuff with this page and I think we should take advantage of how cool the design should be.

For now, my focus is making something that is simple and effective. I want a foundation I can build from later.

**Comment by markstm17** [comment]
I'm fine with originality, I'm just looking forward to something a little more visually appealing. I'm also basing it off of previous experience using the other simple platform (EB) that gets the point across through the designs and their platform template. 

Our goal on this page should be:

1. Show if bus is a "green light" or not yet (Bus is booked and Live)
2. How many spots are on the bus
3. What the current cost is
4. How much money the group has saved from when it became a Live bus, to where cost is now/currently, to what it would be at Max capacity
5. All details for trip
-Pick Up time
-Pick Up Address
-Destination
-Drop off time

Then, adding visuals like the Price-Ometer, place for a picture, the map, etc... whatever you feel would make it look cool and visually appealing, original and unique.


---In the future maybe a dropbox/folder for anyone on that bus to upload photos to after the fact (wayyyyyy down the line, but just thinking as I'm typing this)

**Comment by duncangraham** [comment]
> Show if bus is a "green light" or not yet (Bus is booked and Live)
At this stage, all buses should be green lit. Let's add this soon.

> How many spots are on the bus
agreed

> What the current cost is
agreed

> How much money the group has saved from when it became a Live bus, to where cost is now/currently, to what it would be at Max capacity
not necessary right now, but this is nice and we can add soon.

> All details for trip -Pick Up time -Pick Up Address -Destination -Drop off time
yeap

this is what the page currently looks like

<img width="1390" alt="screen shot 2015-08-05 at 10 54 35 am" src="https://cloud.githubusercontent.com/assets/865298/9093342/749d495e-3b60-11e5-8af6-85ac3271ab74.png">

I'll work on updating this today.

**Comment by markstm17** [comment]
@duncangraham perfect. Same page with this. I agree "Green light" isn't necessary yet, and neither is total price savings. Excited to see this page later

**Comment by markstm17** [comment]
My bad for the duplicate ticket @duncangraham haha

**Comment by markstm17** [comment]
Closing this because of most recent post in #135 

Initial ticket issue of adding picture for trip page no longer relevant right now
