### ISSUE TITLE
Destination Address Field on Create Trip page

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#76]
We will need to have a field that tells the group where Point B is (Destination Field)

I've also mentioned this in #7 in a little bit more detail as to what the create trip page should really look like

**Comment by markstm17** [comment]
To get bare minimum info, all we need is this:

1. Trip Name (Unique to whatever organizer picks)

2. Event and Date/Dates of rental (Just date, no time. Drop down Calendar menu)
----Example: Brewers game 9/17/2015
----Example: Jimmy Buffett 8/22/2015

3. Pick Up Address

4. Pick Up Time

5. Destination Address

6. Drop off Address (If different)

7. Drop off Time

8. Expected number of passengers (not maximum-that is for the bus company, not the organizer)

9. Food or beverage (Often adds $50-$100 to cost)

10. Special conditions/Description/Comments

**Comment by markstm17** [comment]
@duncangraham we need to have a destination Address in the create trip page. Drop off Address is usually referred to after the trip

Point A(s)-Pick up location(s)

Point B-Destination

Point C-Same or Different Box to Check (as Point A) if Same, autofill, if Different input different new or multiple addresses

**Comment by markstm17** [comment]
![screen shot 2015-08-05 at 10 13 50 am](https://cloud.githubusercontent.com/assets/11848699/9089611/9ae582f2-3b5b-11e5-8aaf-7cc52d69ad05.png)

**Comment by markstm17** [comment]
Also, please change Maximum number of passengers to Expected number of passengers

**Comment by markstm17** [comment]
@duncangraham 

Here is what it looks like after I input the info from the screen shot picture above 


![screen shot 2015-08-05 at 10 33 35 am](https://cloud.githubusercontent.com/assets/11848699/9089998/a8d71a4a-3b5d-11e5-879b-848bea7ad317.png)

**Comment by markstm17** [comment]
Delete field, Date is wrong...


Here is what it looks like when I try and edit


![screen shot 2015-08-05 at 10 33 56 am](https://cloud.githubusercontent.com/assets/11848699/9090021/bf12450a-3b5d-11e5-87f8-d58b4a084130.png)

**Comment by duncangraham** [comment]
food and beverage seems like a good field to add, but during the next 2 weeks when we're making the buses ourselves shouldn't the fields be what is on this page?

![screen shot 2015-08-05 at 10 13 50 am](https://cloud.githubusercontent.com/assets/11848699/9089611/9ae582f2-3b5b-11e5-8aaf-7cc52d69ad05.png)

I though this was the bare minimum we needed?

**Comment by markstm17** [comment]
In that case then, Change the Drop off Address to Destination Address @duncangraham 


I may have made it confusing with #7 but the drop off Address is AFTER the trip

Destination Address is during the trip. When I read it (as a former "organizer") in my mind it doesn't give the information for where the bus is headed

**Comment by markstm17** [comment]
Yeah, for Buffett this is perfect @duncangraham but lets please change Drop off address to Destination Address

Also, instead of Max Passenger number, please change to expected number of riders/passengers/partiers (whatever you wanna say)

And Add Food/Beverage field (Check yes or no)

@freindst everything you put together is great, but yeah maybe now we don't need the Event Name, Event Date as it's own fields and as far as drop off location, we will (at least for Buffett) have pick up location be the drop off location as well

**Comment by markstm17** [comment]
So @duncangraham and @freindst 

Above it should be 


1. Trip Name
2. Pick up and Drop off Address
3. Destination Address
4. Pick Up time
5. Final Drop off time
6. Expected number of passengers partying
7. Food and Beverage (Yes or No)



It is more of renaming them to clarify the action of the info needed.


Again in regards to the pricing for me, all that really matters is the time rental. That (for the most part) gives me the dollar amount it will cost to rent bus for group

**Comment by freindst** [comment]
@duncangraham, if you want to set some default value, make sure how it shows on the other pages. At this moment, trip are shown by trip_name, current_price, event_name, event_date, and pick_up_address

**Comment by markstm17** [comment]
@duncangraham Wanna do Create Trip page to what I stated an hour ago above?

8. Any additional comments or specifications about trip

**Comment by markstm17** [comment]
Above it should be

1. Trip Name
2. Pick up and Drop off Address
3. Destination Address
4. Pick Up time
5. Final Drop off time
6. Expected number of passengers partying
7. Food and Beverage (Yes or No Checkbox-Not having the ability to say comments. We aren't providing food/beverages, it just costs $100 more for clean up fees if they decide to bring that on the bus) 
8. Any additional comments/Specifications about trip


Think that looks good @duncangraham and @freindst ??

**Comment by duncangraham** [comment]
from chat, this is how we're moving forward

1. Trip Name
2. Pick up Address
3. Drop off Address (hidden for now, populate with Pick up Address value)
4. Destination Address
5. Event date
5. Pick Up time 
6. Drop off time
7. Expected number of passengers partying (hidden for now, default to 50)
8. "planning on bringing Food and Beverage?" checkbox
9. Any additional comments/Specifications about trip (hidden for now)

**Comment by markstm17** [comment]
Yes

Can we do it in this order from top to bottom for flow of organizer?


1. Trip Name
2. Event Date
3. Pick Up Address
4. Drop Off Address (Same or Different Checkbox---If different then new field for one or more addresses-Hidden for now)
5. Destination Address
6. Pick Up time
7. Final Drop off Time
8. Expected number of passenger partying (Yes default up to 50)
9. "Bringing food and beverage" (Checkbox of yes or no)
10. Any additional comments/Specifications about trip (Hidden for now)

**Comment by markstm17** [comment]
Change the words "Drop Off Address" to "Destination Address"

Also please change the phrase (When do you want to go home?) to

--(When do you want to get home?) ------I used Get, because that will be the drop off time, go insinuates that the bus is about to leave and is still traveling. 
or
--(When do you want your head to hit the pillow?) ***Trying to follow your lead @duncangraham with the quarky puns, remarks and ways to make the UX fun and memorable***


![create trip page](https://cloud.githubusercontent.com/assets/11848699/9104278/0284e1c2-3bd0-11e5-8b9d-b539b537519f.png)

**Comment by duncangraham** [comment]
Destination address is :+1: , but the edits to the return time are confusing.

the return time field is when the bus departs the event to return home, not when it arrives back at the start address. The copy 'when do you want to go home' make sense in this interpretation.

'when do you want to get home' sounds like the time the bus will arrive back at the drop off point, which isn't as important and is nearly impossible to calculate. it would also leave us needing to add another field so people know when the bus is returning.

**Comment by duncangraham** [comment]
changed 'drop off address' to 'destination address'.

**Comment by markstm17** [comment]
@duncangraham for you to better understand the cost of renting the bus if it is rented from 8pm-2am, that is 6 hours. What the bus company actually charges if it is 15 minutes away from the Pick up location is 6.5 hours (They call it dead head time)
--takes 15 minutes both ways to get group which is time which costs $$$


Here is a real world example for us, I have this bus booked for tomorrow night. Don't worry or look at all the "Destinations" for the sake of me trying to get the point of the Drop off Time through to you and @freindst as well. If either of you have questions, let me know

![screen shot 2015-08-07 at 10 47 33 am](https://cloud.githubusercontent.com/assets/11848699/9139803/3d3ce440-3cf2-11e5-8833-8ec28450db21.png)

**Comment by markstm17** [comment]
I'm going to emphasize the 3rd paragraph she asks the question about 2AM

-Either leave bars by then

or

-Final Drop Off

**Comment by markstm17** [comment]
Just trying to communicate the experience of doing this, the costs associated with it, etc...


If need be (through our system) we just shoot on the high end for EVERY bus, instead of trying to be so precise and accurate (Food for thought)

**Comment by freindst** [comment]
I think the create trip page is used to gather information for you @markstm17. Or In another way, it is a way to communication. For example, you should think about what information you might need to give users a good trip plan. If you get enough information, then you do need to contact "organizer" again to figure out what is the best plan for the trip. So, I recommend that we still need precise and detailed information from create trip page.

**Comment by duncangraham** [comment]
I dont think this has any next actions, closing
