### ISSUE TITLE
Visual effect on radio button

### ISSUE THREAD

**Issue by freindst** [ArgoBus/Argo-Project-V0#78]
I have added a some code into main.css in order to show radio button. As I am not familiar with css, I just copy a piece of codes. Right now, it looks terrible:
![image](https://cloud.githubusercontent.com/assets/13219475/9074844/a09cc512-3ad3-11e5-8f69-12ccf0cf7cb7.png)
@duncangraham: Can you make it look better?

**Comment by duncangraham** [comment]
@freindst what view is this on? what are the radio buttons controlling?

**Comment by freindst** [comment]
admin page -> select any trip -> insert(update) template ->
Admin is going to choose a template for a trip.

**Comment by freindst** [comment]
**Admin page**
![image](https://cloud.githubusercontent.com/assets/13219475/9094289/870de952-3b76-11e5-8489-ebb229ea8041.png)
**Select a trip**
![image](https://cloud.githubusercontent.com/assets/13219475/9094303/9efcd0b4-3b76-11e5-9848-646e06c5e954.png)
**update template**
![image](https://cloud.githubusercontent.com/assets/13219475/9094312/b125e0f0-3b76-11e5-80cb-bbd2cad23c5d.png)
radio button is that box before "Template 1"

**Comment by markstm17** [comment]
For Buffett (Trip number 1) we will only use this "template"

0-10 = $60
11-20= $50
21-30= $40
31-40= $30
41-50 =$20


And I'd actually like to make it available for 55 people to come on the bus so final node is 41-55 = $20

**Comment by freindst** [comment]
You can create template at admin page when you want to insert a template to a trip.
I will show you the how process:
 1. Organizer(common user) create a trip
![image](https://cloud.githubusercontent.com/assets/13219475/9094716/1a3dc4ac-3b79-11e5-9512-0d86b15dc098.png)
2. Administrator go to admin page find the trip is not ready(no template)
![image](https://cloud.githubusercontent.com/assets/13219475/9094743/3f935b54-3b79-11e5-8a8a-b94d6915da24.png)
3. Admin click the trip, insert a template
![image](https://cloud.githubusercontent.com/assets/13219475/9094764/588048fc-3b79-11e5-92c3-ab7630372412.png)
4. You can create a template or choose existed template
![image](https://cloud.githubusercontent.com/assets/13219475/9094877/ded88e28-3b79-11e5-93cb-de98fb684ded.png)
5. create a template
![image](https://cloud.githubusercontent.com/assets/13219475/9094846/b932b5b8-3b79-11e5-83df-639f9ab03f10.png)
6.finished
![image](https://cloud.githubusercontent.com/assets/13219475/9094869/d545bf66-3b79-11e5-8337-f222266e76ec.png)

**Comment by markstm17** [comment]
This is awesome. @duncangraham this is what we talked about where the code/algorithm ultimately automatically makes this manual process that @freindst created happen (Based upon rental time and mileage)

Great for us now (as the organizers, because we can set the templates as we learn throughout some of these trips) 

I think it looks good Blade, I'm excited to test it out. 

What do you think of it @duncangraham ?

**Comment by duncangraham** [comment]
stale
