### ISSUE TITLE
8/5 night test problem

### ISSUE THREAD

**Issue by freindst** [ArgoBus/Argo-Project-V0#87]
1. Create template page - change fonts color
![image](https://cloud.githubusercontent.com/assets/13219475/9103695/b8a0fa4a-3bc6-11e5-8ca5-4ba6d07f4e5f.png)
2. By email, admin can directly lead to the insert template function. Otherwise, admin has to input url(www.argobus.com/admin) manually.
3. During other test, I noticed that the default page when user needs authentication is sign up page. However, sign up button is the only thing to tell user that he is in a sign up page not a log in page. Can you put a title or other more explicit way to tell user?
![image](https://cloud.githubusercontent.com/assets/13219475/9103929/ea0afbfa-3bc9-11e5-9d76-b595cfc1227e.png)

**Comment by duncangraham** [comment]
yea, I know exactly how to clear this up. i'll work on it.

**Comment by duncangraham** [comment]
stale
