### ISSUE TITLE
Email-Admin to Organizer Edit Example 8/5/2015

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#91]
![email-admin](https://cloud.githubusercontent.com/assets/11848699/9104543/624a922a-3bd3-11e5-856b-8e7624e3ea6f.jpg)

Same concept as what I just said about #90 

Here are some examples:

1. Congrats! There's a lot to be excited about! The link below will help create lots of memories! Share, Share, Share!
2. Send this to one friend. Then tell that person to send this to one friend. If you do it 50 times you'll likely fill your bus, have a blast and have some new friends!
3. This link will change your life. Share it with everyone! (Except that friend that nobody likes named Karen-Dane Cook Joke)
4. Dancing Shoes, Check. Hula Skirt and coconut bra, check. It's 5 o'clock somehwere, check. That link helps you get to Margaritaville. Care to Share?
5. Green Bay Packers Tickets, $100. New Aaron Rodgers jersey, $75. Beer and Food at Lambeau Field, $40. Current Price for the bus, $60. Future price for the bus, $20.

Etc... Etc... Etc...

**Comment by freindst** [comment]
You can organize some samples, and I shall insert into email function as randomly pickup usages and phreases.

**Comment by markstm17** [comment]
Closing
